In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_excel(r'original Exports by Countries preformatting.xls')

In [3]:
data.shape

(2013, 15)

In [4]:
data.dtypes

Year           int64
Country       object
Total        float64
January       object
February      object
March         object
April         object
May           object
June          object
July          object
August        object
September     object
October       object
November      object
December      object
dtype: object

In [5]:
data.head(5)

,Year,Country,Total,January,February,March,April,May,June,July,August,September,October,November,December
0,2021,France,8.109804e+06,736850,753879,817811,771909,656915,806028,563530,743857,691820,780876,786330,NaN
1,2021,Netherlands,6.171188e+06,402104,455219,532448,609578,520072,724931,533652,612951,594277,548346,637610,NaN
2,2021,Germany,1.754488e+07,1.45219e+06,1.49354e+06,1.67427e+06,1.65319e+06,1.40623e+06,1.70343e+06,1.4452e+06,1.57187e+06,1.69446e+06,1.69109e+06,1.7594e+06,NaN
3,2021,Italy,1.032350e+07,865094,831861,977428,887519,830622,1.08121e+06,796743,806351,1.02019e+06,1.10241e+06,1.12407e+06,NaN
4,2021,United Kingdom,1.237214e+07,812406,960581,1.06133e+06,1.03773e+06,1.10088e+06,1.26915e+06,981434,1.18902e+06,1.25957e+06,1.22135e+06,1.47871e+06,NaN

In [6]:
data.sample(15)

,Year,Country,Total,January,February,March,April,May,June,July,August,September,October,November,December
320,2020,Kenya,227998.029,17814.5,15403.5,27458.8,13383.6,16715.8,16503.4,15235.4,13465,20779.6,24116.6,19649.5,27472.3
1769,2014,Papua New Guinea,3960.702,23.496,775.595,744.019,411.811,618.321,270.539,346.743,9.48,193.837,34.537,200.991,331.333
796,2018,Belize,9941.248,419.015,513.048,870.392,400.825,411.165,1041.56,978.879,1078.64,1077.99,886.095,1638.43,625.214
1137,2016,Melilla,48.466,-,-,-,-,48.466,-,-,-,-,-,-,-
911,2017,Ireland,541550.711,45152.9,32194.4,47211.9,51265,39149.7,38302.2,31402.5,36794.1,32056,62848.3,63935.2,61238.5
74,2021,Ghana,414053.601,31016,28209.7,41252.4,42680,33158.3,39034.3,28360.8,40376.4,38863.1,42446.9,48655.6,NaN
1130,2016,Denmark,984215.747,79553.3,85793.7,77001.2,73865.5,70575,84767.8,77492.2,82951.9,79842.5,85961.1,81231.6,105180
1196,2016,Guinea,71673.022,6688.51,3522.41,9517.09,6368.72,5696.17,9999.66,2268.07,4863.39,7858.09,3032.78,5858.07,6000.08
1004,2017,Mauritius,65450.279,20840.4,3862.58,3158.11,4333.31,3059.1,3290.93,4671.45,4317.27,3595.42,5210.09,4633.94,4477.64
935,2017,Slovakia,405376.727,27053.3,30548.1,36172.2,34657.5,32769.4,33470.6,30392.8,35711.7,33624.2,38945.2,41282.4,30749.5
1826,2013,Bulgaria,2136157.181,132309,152569,207905,171615,178498,171284,183596,157487,194218,193345,218275,175056
471,2019,Switzerland,1039832.982,61859.4,63615.4,71198.6,74616.6,94996.3,97828.3,121996,138363,78360.6,86124.9,77460.6,73413.4
1942,2013,Bolivia,16907.076,1499.97,1259.86,910.899,1045.96,1902.81,1086.6,1560.95,1913.72,871.208,1651.54,1456.42,1747.14
1539,2015,North Korea,4660.705,-,-,659.194,863.047,8.636,3.04,877.3,-,843.554,670.185,735.749,-
1659,2014,Eritrea,6285.497,104.318,41.948,200.273,10.193,346.552,4286.53,189.469,159.234,270.232,149.024,408.719,119.002

In [7]:
#data = data.rename({'Unnamed: 0' : 'Country code'}, axis = 1).to_excel(r'Exports_by_Countries_preformatting.xls')

In [8]:
calendar = list(data.columns)[3:]
calendar

['January',
 'February',
 'March',
 'April',
 'May',
 'June',
 'July',
 'August',
 'September',
 'October',
 'November',
 'December']

In [9]:
data[data.isin(['-']).any(axis=1)]

,Year,Country,Total,January,February,March,April,May,June,July,August,September,October,November,December
12,2021,Ceuta,0.128,0.128,-,-,-,-,-,-,-,-,-,-,NaN
24,2021,San Marino,338.583,-,73.075,26.106,117.291,1.966,53.597,1.517,6.581,1.761,28.801,27.888,NaN
87,2021,St. Helena And Dep.,687.093,-,32.83,37.473,78.786,12.324,103.664,31.436,164.745,23.614,202.221,-,NaN
97,2021,British Ind.Oce.Ter.,255.630,21.348,-,0.424,-,-,121.422,-,3.494,-,108.942,-,NaN
114,2021,St Pierre and Miquelon,0.020,-,-,-,0.02,-,-,-,-,-,-,-,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2005,2013,American Samoa,222.228,16.433,5.561,1.894,-,4.653,19.696,76.009,-,-,7.091,78.011,12.88
2007,2013,USA Minor Outlying Islands,136.208,28.225,13.451,25.084,-,4.397,-,-,50.11,-,-,2.445,12.496
2008,2013,Christmas Islands,112.000,-,-,-,-,-,-,-,-,112,-,-,-
2010,2013,South Georgia and Sandwich. Isl.,3.959,-,-,-,-,-,-,-,-,3.959,-,-,-
2011,2013,French Southern Territories,607.169,-,-,16.405,140.752,-,-,28.581,141.527,80.046,82.321,117.537,-

In [10]:
data.replace(to_replace = '-', value = 0, inplace = True)
data.sample(10)

,Year,Country,Total,January,February,March,April,May,June,July,August,September,October,November,December
944,2017,Georgia,1337799.502,75483.915,94094.663,107351.817,100090.595,109824.787,114357.138,105630.121,128027.925,108795.862,131876.673,131553.911,130712.095
1362,2015,Norway,456156.440,65543.630,33226.810,26553.646,52460.801,37332.605,35325.041,38674.776,57782.503,44853.039,20660.994,21370.612,22371.983
1254,2016,Turks And Caicos Isl,145.943,0.000,30.050,1.991,19.147,0.000,0.000,0.000,21.656,34.485,21.656,16.958,0.000
1039,2017,St. Lucia,1948.150,169.987,164.395,195.397,132.157,19.090,286.560,38.895,63.058,267.241,8.177,70.317,532.876
555,2019,Mayotte,6232.778,1163.635,459.809,297.277,341.652,737.863,231.294,237.055,940.313,586.339,585.790,385.033,266.718
496,2019,Turkmenistan,744691.111,34576.027,47104.398,50129.589,55992.892,70975.718,46744.524,78598.225,73081.765,72506.912,76230.037,68627.391,70123.633
430,2020,Solomon Isl.,179.608,12.114,0.000,0.000,0.000,7.901,61.073,0.000,16.988,45.367,32.385,0.000,3.780
1701,2014,Antigua and Barbuda,15818.928,489.535,539.911,384.070,1856.444,2327.001,1854.665,2087.839,902.467,1630.329,1787.388,738.094,1221.185
1383,2015,Albania,293693.349,16031.844,18326.314,21329.467,21648.521,25040.502,26446.538,22870.101,27542.965,25340.706,26282.676,29760.381,33073.334
1668,2014,Madagascar,54372.335,4557.393,2974.870,4040.175,2898.833,3800.327,4967.931,4722.875,5680.124,6995.354,5004.469,4728.205,4001.779

In [14]:
data.to_excel(r'Exports by Countries formatting.xls', index = False)
data.sort_values(by = ['Year', 'Total'], ascending = False).to_excel(r'Exports by Countries formatting.xls', index = False)
data = pd.read_excel(r'Exports by Countries formatting.xls')
data.head(10)

,Year,Country,Total,January,February,March,April,May,June,July,August,September,October,November,December
0,2021,Germany,1.754488e+07,1452190.805,1493543.790,1674271.321,1653187.402,1406227.126,1703430.634,1445203.512,1571869.836,1694461.008,1691091.589,1759404.069,NaN
1,2021,USA,1.320764e+07,931743.457,914686.199,1243574.256,1184111.978,1152494.529,1347959.791,1056265.265,1309740.730,1387959.978,1306058.514,1373049.996,NaN
2,2021,United Kingdom,1.237214e+07,812405.518,960580.550,1061325.205,1037726.446,1100878.008,1269147.889,981433.772,1189018.557,1259570.787,1221346.117,1478707.617,NaN
3,2021,Italy,1.032350e+07,865093.684,831861.252,977428.472,887518.532,830622.255,1081205.941,796743.189,806350.741,1020193.146,1102414.165,1124071.100,NaN
4,2021,Iraq,9.970224e+06,695843.429,751920.777,926926.603,922625.234,678833.384,911687.420,771260.959,937525.376,1029022.232,1129138.203,1215440.734,NaN
5,2021,Spain,8.786285e+06,652274.857,685454.998,794045.895,778911.905,714029.400,764357.714,765793.078,836945.456,949717.170,986034.504,858720.504,NaN
6,2021,France,8.109804e+06,736849.754,753879.350,817810.720,771908.812,656914.536,806027.677,563530.014,743857.264,691820.311,780875.965,786329.530,NaN
7,2021,Netherlands,6.171188e+06,402103.778,455219.126,532447.690,609578.213,520071.822,724931.044,533651.527,612950.643,594277.336,548346.432,637610.061,NaN
8,2021,Israel,5.664540e+06,404181.585,448608.598,528607.605,549354.038,424920.185,544878.890,454391.777,558454.759,528860.309,604757.277,617525.433,NaN
9,2021,Russia,5.186535e+06,353114.891,383245.118,445988.086,468103.828,440449.832,541422.896,417377.349,451188.741,504403.090,615954.690,565286.767,NaN

In [16]:
data.shape

(2013, 15)

In [17]:
countries = [state for state in data['Country'].unique()]
years = [x for x in range(2013, 2022)]
years_change = ['13/14', '14/15', '15/16', '16/17', '17/18', '18/19', '19/20', '20/21']
dfGDPchange = pd.DataFrame(columns = ['Country', '13/14', '14/15', '15/16', '16/17', '17/18', '18/19', '19/20', '20/21'])

In [18]:
#data = data.drop(columns = 'Country code')
data.columns

Index(['Year', 'Country', 'Total', 'January', 'February', 'March', 'April',
       'May', 'June', 'July', 'August', 'September', 'October', 'November',
       'December'],
      dtype='object')

In [19]:
pdata = data

keylist = ['Year', 'Country', 'Total'] + calendar
dict_country = {}
for i in keylist:
    dict_country[i] = None

for state in countries:
    for y in years:
        if state not in pdata[pdata['Year'] == y]['Country'].unique():
            dict_country['Year'] = y
            dict_country['Country'] = state
            dict_country['Total'] = 0
            for m in calendar:
                dict_country[m] = 0
            #print(dict_country, '\n')
            pdata = pdata.append(dict_country, ignore_index = True)
pdata.tail()

,Year,Country,Total,January,February,March,April,May,June,July,August,September,October,November,December
2128,2017,Saint Barthelemy,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2129,2018,Saint Barthelemy,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2130,2019,Saint Barthelemy,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2131,2020,Saint Barthelemy,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2132,2021,Saint Barthelemy,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
pdata = pdata.sort_values(by = ['Year', 'Total'], ascending = False)
pdata[pdata['Country'] == 'Melilla']

,Year,Country,Total,January,February,March,April,May,June,July,August,September,October,November,December
2116,2021,Melilla,0.000,0.0,0.0,0.0,0.00,0.000,0.000,0.00,0.000,0.000,0.0,0.000,0.000
2115,2020,Melilla,0.000,0.0,0.0,0.0,0.00,0.000,0.000,0.00,0.000,0.000,0.0,0.000,0.000
2114,2019,Melilla,0.000,0.0,0.0,0.0,0.00,0.000,0.000,0.00,0.000,0.000,0.0,0.000,0.000
2113,2018,Melilla,0.000,0.0,0.0,0.0,0.00,0.000,0.000,0.00,0.000,0.000,0.0,0.000,0.000
2112,2017,Melilla,0.000,0.0,0.0,0.0,0.00,0.000,0.000,0.00,0.000,0.000,0.0,0.000,0.000
1337,2016,Melilla,48.466,0.0,0.0,0.0,0.00,48.466,0.000,0.00,0.000,0.000,0.0,0.000,0.000
2111,2015,Melilla,0.000,0.0,0.0,0.0,0.00,0.000,0.000,0.00,0.000,0.000,0.0,0.000,0.000
2110,2014,Melilla,0.000,0.0,0.0,0.0,0.00,0.000,0.000,0.00,0.000,0.000,0.0,0.000,0.000
1986,2013,Melilla,545.983,0.0,0.0,0.0,137.95,0.000,204.082,53.39,70.638,11.364,0.0,57.296,11.263

In [21]:
def country_absence():
    x = 0
    for state in countries:
        for y in years:
            if state not in data[data['Year'] == y]['Country'].unique():
                x += 1
    return x

In [23]:
#checking
print(data.shape)
print(pdata.shape)
print(pdata.shape[0] - data.shape[0] == pdata[pdata['Total'] == 0].shape[0])
print(pdata.shape[1] == data.shape[1] == pdata[pdata['Total'] == 0].shape[1])
print(country_absence())
print(pdata[pdata['Total'] == 0].shape)

(2013, 15)
(2133, 15)
True
True
120
(120, 15)

In [24]:
pdata.to_excel(r'Exports_by_Countries_preformatting_filled.xls', index = False)

In [25]:
countryExpchange = {}
for state in countries:
    listTotal = pdata[(pdata['Country'] == state)][['Year', 'Total']].sort_values(by = ['Year'], ascending = True)
    listTotal = listTotal['Total']
    listcountry = []
    for x in range(1,9):
        if listTotal.iloc[x-1] != 0:
            listcountry.append(100*((listTotal.iloc[x]/listTotal.iloc[x-1]) -1))
        else:
            listcountry.append(None)
    countryExpchange[state] = listcountry

In [26]:
countryExpchange

{'Germany': [9.727399107701217,
  -10.967135545120854,
  4.654996871675032,
  7.856521731919908,
  6.09578855840891,
  -4.242381435759935,
  -3.8426714287329578,
  9.801693182710158],
 'USA': [4.129094860908422,
  1.4251025166786224,
  3.4564001158114532,
  27.501969972163387,
  -2.0176560466881543,
  -1.1253287769494635,
  13.514147079083806,
  29.70331947072078],
 'United Kingdom': [11.940156168021176,
  5.935226618758405,
  10.5223978035623,
  -16.963636386533754,
  15.518575815232062,
  -1.7022234857504648,
  -0.3815489255672766,
  10.115708806242797],
 'Italy': [0.1633410618922415,
  -4.457045107863367,
  9.854011585745281,
  11.839162150155103,
  14.332165323093005,
  -2.9304418963054246,
  -17.127595885332493,
  27.725646368698186],
 'Iraq': [1.5771612801326995,
  -24.231746700490987,
  -14.754995491604427,
  18.994070136432395,
  -6.655102323167195,
  8.331932202337388,
  -10.576292885344662,
  9.058993239776235],
 'Spain': [9.290168555243028,
  -0.5842988098871293,
  5.662559074158158,
  25.9400918330007,
  23.32868736585929,
  0.2173098415005903,
  -17.880592630193682,
  31.46256895921724],
 'France': [3.0322844077008915,
  -11.012396557503191,
  3.4091900280442955,
  9.285569368799408,
  11.02335730416415,
  3.791696298816283,
  -9.444705685803623,
  12.7118142740267],
 'Netherlands': [-3.4258112954879127,
  -8.249359199890039,
  14.648093989895749,
  9.016984755129531,
  21.7272579434731,
  12.962374067747318,
  -9.83702962148606,
  18.788174824232318],
 'Israel': [9.008142284748711,
  -8.384860189968446,
  8.837297964443124,
  14.739884946005045,
  14.780337330545201,
  10.960856584448408,
  5.382557355533568,
  20.417406116183344],
 'Russia': [-14.464336284158197,
  -40.29185063512779,
  -51.33582579986514,
  60.0659041650728,
  27.275176756785015,
  13.676099948362562,
  8.538820803023238,
  15.085486965054962],
 'UAE': [-5.79441142089957,
  -0.09231998914435158,
  12.300998616341928,
  67.20677387914004,
  -64.88599605057568,
  11.46945096395564,
  -22.033132481521456,
  73.06795232678537],
 'Romania': [12.84987748601063,
  -6.902893937928778,
  -4.2046613282589735,
  18.326274883859426,
  24.8016919469247,
  -1.5532528879066754,
  -4.397022351218938,
  20.45576848720403],
 'Belgium': [12.522476717191022,
  -14.613438310728489,
  0.13983886356756514,
  23.31333127563473,
  23.43767360164022,
  -18.21429247200924,
  7.021974882101145,
  23.388024476633042],
 'Poland': [16.21700344814634,
  -2.584966401578659,
  13.741668650219175,
  15.76205307930405,
  9.454304506825672,
  -1.1242279980782643,
  0.7508854252175512,
  22.398742664776705],
 'Egypt': [3.1739146911965443,
  -5.6122398483672065,
  -12.83506648280075,
  -10.03731436758425,
  26.17703253015906,
  9.146617926307643,
  -10.619931139412342,
  24.622501857875577],
 'Bulgaria': [-0.8811306661988372,
  -16.74424953791379,
  41.146990550160844,
  17.34827040646394,
  -3.5208373389037484,
  -5.280896600887863,
  -1.2662288687917078,
  35.43838706228408],
 'China': [-20.9022684796637,
  -15.822050908750606,
  -4.882012769015143,
  27.71187152620158,
  1.3487016039251287,
  -11.452012269272249,
  5.127818596499867,
  17.861913540837413],
 'Greece': [8.070023724785313,
  -10.797670299679506,
  -1.0832290556868407,
  17.08937907231334,
  34.73046685333703,
  -3.3440691056388694,
  -19.84047609891316,
  56.25181057449862],
 'Ukraine': [-22.271019318454034,
  -36.35608635799883,
  12.657577292742971,
  10.165859681819,
  14.887074893576457,
  28.043551843444803,
  -3.0664631336757453,
  26.576121096700067],
 'Morocco': [10.45547597096046,
  -5.257415927293185,
  8.63194539157881,
  13.217577614932496,
  20.72598848761107,
  15.278218341162209,
  -12.364830974623208,
  27.18506141915573],
 'Iran': [-7.041912344597323,
  -0.6563562656474842,
  32.73101973184887,
  -29.321538423241368,
  -28.356022408791194,
  -1.034891294040008,
  -17.686488336588702,
  12.588259380373291],
 'Libya': [-30.832058261896165,
  -29.967821004598726,
  -35.437593728470596,
  -6.505681241795225,
  72.9250622087599,
  30.688268342473002,
  -20.12183365648672,
  51.73370752681943],
 'Azerbaijan': [-3.568396627679815,
  -31.654439664664945,
  -33.66402155552821,
  6.386420711873919,
  15.265948101205652,
  5.080676939685658,
  16.603901339900062,
  1.6948854164045901],
 'Syria': [90.07757116072361,
  -19.21933872569097,
  -5.687032693405758,
  -0.22177803121280482,
  0.6735499323761607,
  -3.2112518579623828,
  -7.805984878003736,
  20.25977711123781],
 'Uzbekistan': [4.142988767539313,
  -20.326928814887978,
  7.964300224905796,
  29.90467023275172,
  41.813650877612815,
  19.550996681525625,
  -6.330363644377613,
  46.75760890504876],
 'Slovenia': [8.602318002640352,
  8.812429361458962,
  14.593399893994995,
  24.746377515491226,
  28.072807533163413,
  22.27758770218504,
  -10.951276766103978,
  -3.5176552053057475],
 'Canada': [1.4208781112770907,
  -27.246305441581498,
  8.451566318436242,
  41.21121186585752,
  21.722382403142237,
  -26.34759537564918,
  1.969752137230052,
  55.57132548423751],
 'Sweden': [13.341275269945264,
  -11.358216564055535,
  1.8825477055580686,
  12.74952588648497,
  4.831541603198386,
  -6.612764788037573,
  -7.126835944199527,
  16.76224392543153],
 'Algeria': [5.14188138400562,
  -13.39248410037741,
  -5.285817927809466,
  -0.11519010839126098,
  16.0153925290623,
  -4.926627487968094,
  -28.1123999110261,
  5.439154263817714],
 'Georgia': [14.357487147066482,
  -21.924975622551955,
  4.584879245930074,
  1.6766513408526862,
  7.536155444016601,
  9.689575430854136,
  -7.398968159945063,
  4.434762823531302],
 'Czech Republic': [15.076081141686526,
  -6.955981820639289,
  4.397905452996076,
  10.562514571726854,
  10.81310536939084,
  -4.277713876976319,
  1.3576151388059454,
  34.40897998608614],
 'Lebanon': [-54.88426178270457,
  -11.293597969831904,
  4.617066599749697,
  19.5732287896351,
  0.44179978862761704,
  15.342038422660353,
  -16.267184571648585,
  58.70552437656937],
 'Austria': [6.479272268739278,
  -9.414355528596975,
  2.4695853438226667,
  7.1455773053947125,
  5.102830203418729,
  -1.8217342142130333,
  -4.520332067113387,
  22.418101653454748],
 'Portugal': [-8.385831153626789,
  -0.7704128841948932,
  16.741345311973266,
  24.21284113590083,
  37.03681779653847,
  -0.00021263841017971075,
  -19.39305386656064,
  46.537488933672535],
 'Serbia': [14.096907734042974,
  0.35338267051900907,
  19.712094029823035,
  22.874772906381025,
  20.333595412911443,
  4.204766237521662,
  6.69854462158177,
  32.700068131375915],
 'Hungary': [9.109732294367623,
  3.4676309848513,
  18.2218228427087,
  27.27962743779284,
  8.849031153192133,
  8.409385610708075,
  -11.227436601963669,
  3.066923514452813],
 'Tunisia': [-7.377939108296749,
  -10.94955749689247,
  10.479196143745995,
  0.24024800610082941,
  2.071854430658715,
  -7.586609082483376,
  4.66390297574395,
  34.184914493702266],
 'Kazakhstan': [-5.954200527945474,
  -18.828111215796163,
  -19.098068903469134,
  17.722858970214574,
  -5.952105437511146,
  13.896367839472145,
  9.495305220231032,
  19.791769076288368],
 'Denmark': [7.978034454102434,
  -15.731532401248337,
  5.326131282951829,
  6.8574644538785146,
  6.068822000546303,
  -6.868874897988563,
  0.5020059377176311,
  12.193113232307118],
 'Switzerland': [191.90471673605253,
  76.23545956122241,
  -52.07058287226127,
  -66.3463647566422,
  93.44750668314379,
  -41.61076153496235,
  5.204232788992269,
  2.5239535289158566],
 'Turkish Rep. of Nor.Cyprus': [5.088364967026315,
  -14.681143274334064,
  -11.001745993624557,
  19.825506924769833,
  10.704665417211379,
  3.8898304185309485,
  -33.76416105256772,
  28.92083668734793],
 'India': [0.476800264951982,
  12.859075189637338,
  -0.9720647518473791,
  16.922854661527275,
  46.19179411516012,
  -1.3303592907502826,
  -23.72535496876509,
  24.10052458445735],
 'Qatar': [43.67744491562979,
  18.335054490905158,
  12.379431930573826,
  62.58986374057955,
  57.32363746438003,
  3.92900331267354,
  -19.796887028416066,
  1.2125275490448173],
 'Yemen': [6.48410209554493,
  -38.552354955404454,
  35.99529333652776,
  6.054745214641,
  28.02123425815688,
  30.94741927586515,
  -13.93584231071172,
  23.573440201524566],
 'Hong Kong': [2.7521975418512534,
  -21.016301522952585,
  14.596188341070127,
  58.88649580439535,
  28.01697951972546,
  -10.67595702263404,
  9.954569069060204,
  20.74870578978809],
 'Brazil': [-15.159705317760718,
  -41.60716243651426,
  -28.4089083090998,
  17.425835438532022,
  26.290552330562143,
  -2.5301462070005165,
  18.975163950269636,
  63.59617523854819],
 'Turkmenistan': [15.480949816243506,
  -16.876848914946795,
  -30.432687212872413,
  -18.360851297132484,
  -54.981077290041625,
  47.99209894397269,
  5.674922175887187,
  16.562648430319538],
 'Australia': [-11.447556896889655,
  -2.3467848644344147,
  24.481691641596214,
  -14.93961971943537,
  25.13152815182771,
  -6.098622709245416,
  9.937967130973014,
  21.932367198276935],
 'Norway': [-10.071516944829884,
  -18.846040325684545,
  24.852907042154214,
  -0.819714055675802,
  -7.540497973516624,
  39.61905046563308,
  0.5714622790129242,
  17.712032391092137],
 'South Korea': [2.695052333259418,
  20.056776767131556,
  -10.198357589249419,
  12.293292526813705,
  58.08987519628577,
  -3.9344723086979116,
  16.95372086287119,
  -22.71132084037476],
 'Ireland': [24.17850748879282,
  -0.6889404524076048,
  6.66761566900973,
  7.327576482986253,
  42.34523643714687,
  -19.572543491157614,
  5.591296447603655,
  28.25389951773436],
 'Belarus': [-10.204671101110574,
  -23.938060371618608,
  71.18823798003979,
  18.1702401987617,
  3.90314468727766,
  19.07154045417485,
  10.98006904020512,
  34.944556309136374],
 'Rep. of South Africa': [-11.633024908837019,
  -11.918724412624716,
  -18.994027451869734,
  16.33730055243685,
  12.55124941180048,
  2.763800746806022,
  0.784742897668389,
  40.333431719704535],
 'Singapore': [5.367030020244212,
  14.228821485613953,
  -4.475527698460013,
  64.99682175714811,
  -17.817737662581568,
  29.514687246686734,
  -54.21699355074829,
  131.52606287015428],
 'Nigeria': [7.815627582097018,
  -26.334619901714305,
  -33.99663724583847,
  37.26526152208562,
  8.28075319349777,
  61.63374505363846,
  2.5134674997729034,
  27.01293651198271],
 'Mexico': [23.90776818840248,
  8.38479822173197,
  27.914524425879293,
  0.38990421693188004,
  36.58017244629674,
  2.463506182414199,
  -19.416790377436932,
  38.15844627702136],
 'Albania': [1.9906123958789212,
  -10.437308025935721,
  6.359482795097282,
  29.172227780485915,
  6.558901974565456,
  13.316372219481632,
  -2.437942274748184,
  48.462848951614724],
 'Jordan': [22.938712640966475,
  -8.325440050571153,
  -13.922312199127607,
  -5.497527087386544,
  25.908533790081666,
  -24.991740636495553,
  -12.28154586523289,
  19.881867081006565],
 'Pakistan': [22.638816588823275,
  -36.2450642673426,
  24.133795977442695,
  0.8621281779264356,
  34.9994073526851,
  8.053663429443446,
  12.723298662484916,
  8.352020347356138],
 'Kyrgyzstan': [8.145538051576985,
  -32.14702970463171,
  3.348847017111156,
  15.625196548311827,
  3.393543388065079,
  12.784396199318238,
  -5.546284418884239,
  58.72798461880022],
 'Malta': [7.994671426486288,
  -48.165722602721125,
  -54.139095741009,
  125.4148031228044,
  3.7216492070560436,
  65.8928909770384,
  -54.73374600599049,
  46.39164336957744],
 'Kuwait': [18.704973951809723,
  23.06804767393038,
  -11.842961032586652,
  3.5759111931477516,
  20.087189334069787,
  1.4445884220203764,
  -0.2513746200108691,
  11.633834757596917],
 'Slovakia': [14.176865604896992,
  5.457442503567966,
  -27.347778674111723,
  0.12183630176301197,
  36.31905341225965,
  8.36594276493885,
  -8.167349447756934,
  8.94492925859911],
 'Bosnia and Herzegovina': [16.747955549020578,
  -9.092438826468264,
  7.300076137671718,
  12.186225636320236,
  20.927886040091504,
  5.232330126137219,
  -1.5238157833987076,
  30.643610501665197],
 'Chile': [-10.006706071855698,
  -5.63452418764403,
  15.934027748480162,
  18.701423683512886,
  50.96502565694168,
  -10.446790456003875,
  -21.446754489465125,
  103.0991189884932],
 'Peru': [4.381163121519482,
  -31.385543588982788,
  -55.717225206708164,
  25.62085005928447,
  57.22777764507641,
  3.915374061656718,
  27.970834654335764,
  132.7603081598473],
 'North Macedonia': [17.310141158117375,
  -4.9457463232204235,
  17.248667393404805,
  -3.909247310191988,
  8.600344910856418,
  -1.052607501345093,
  1.7272688027925254,
  22.76342381997065],
 'Kosovo': [-2.8605066872210205,
  -12.021516861937487,
  8.628000688187655,
  3.7207661832474592,
  11.046711284644495,
  10.954083628022882,
  4.757646959659989,
  37.26428368018744],
 'Bangladesh': [-7.644328494034203,
  8.25232031401204,
  25.356315347570014,
  2.1774753194211405,
  36.356070622289316,
  -9.951632844978775,
  -18.288462272602825,
  42.417386208188375],
 'Senegal': [36.32361710691077,
  -21.966929697390192,
  22.392696732814343,
  54.459263764009535,
  57.57438231991554,
  -26.679386072081314,
  25.01813355299134,
  34.67625180134737],
 'Finland': [9.708458970802836,
  -19.282502764466138,
  9.785480685993807,
  3.1630594594965755,
  12.633659763700923,
  -2.5865457614348664,
  10.591907061743244,
  26.463664554856315],
 'Oman': [26.952683641776986,
  -33.39843763776843,
  -24.743741515037588,
  -6.661898797877919,
  89.71834675829659,
  44.48190887141838,
  -17.209836573508873,
  -12.739043630630098],
 'Croatia': [13.87511316681267,
  -14.2662862544229,
  9.686121871307174,
  13.154746262372786,
  29.811780836945868,
  6.551300121208281,
  -11.621334233576896,
  15.032959567203296],
 'Japan': [-8.791199915263903,
  -10.389743332997858,
  5.302118792709187,
  15.916473870914437,
  18.59394286666596,
  1.8349759871549631,
  -12.251864892379293,
  -1.8583100821292442],
 'Ghana': [0.19677691796211594,
  25.695783551422014,
  28.840831430683767,
  -24.35788699483965,
  22.082883692741675,
  33.702346205630775,
  27.566027173251626,
  -13.292712751776447],
 'Moldova': [7.4804735531802,
  -30.28581589454914,
  25.12694685919925,
  9.702133549421287,
  -5.262226283779404,
  18.381781947150234,
  -2.4166933773929977,
  20.56834752360015],
 'Malaysia': [15.262985630744218,
  12.468027068232956,
  -9.774042552756523,
  -10.915980142459647,
  28.082643803718543,
  -5.708198024292798,
  7.812306455409446,
  4.540513089520504],
 'Mauritania': [-9.677254302110471,
  4.016019556734451,
  -21.075632664051714,
  13.001917210211356,
  63.49891824737857,
  15.841601758977575,
  -28.8956235773528,
  231.47910646002114],
 'Colombia': [34.08931425527308,
  2.4526801549125343,
  -0.19614346990703968,
  0.6936154869531252,
  30.199418009875558,
  3.515353525197762,
  -15.408570748100182,
  81.645354344868],
 "Côte d'Ivoir": [6.398231736498938,
  28.385067843272573,
  -2.372259709111646,
  29.708860116560842,
  16.041738256278904,
  27.047518105336188,
  35.2443343021799,
  18.516112483571924],
 'Lithuania': [-11.747612079137248,
  -14.909621609551094,
  -9.471285281636622,
  13.58184585733262,
  -8.588305263117736,
  -12.05749919869098,
  18.401996097868345,
  9.189399305090596],
 'Somalia': [4.063567923206302,
  13.849029881581764,
  65.28497443605292,
  22.9699601031643,
  24.721072541310086,
  39.477536250480696,
  5.914590898237737,
  15.442912356836413],
 'Vietnam': [55.597193201804586,
  -7.961031413650832,
  49.83940719926516,
  2.27275574806447,
  29.543105283804284,
  9.425958476456175,
  -30.47464290097611,
  24.611884216465185],
 'Ethiopia': [-9.446827490922038,
  17.019622338737882,
  4.637100886414336,
  -15.631153945580733,
  -5.34173091283463,
  15.880756067584102,
  -39.25676871920704,
  30.2436573115054],
 'Djibouti': [-13.85639084557294,
  62.14836849799037,
  -16.936043772206933,
  26.352415160096587,
  90.44808333736418,
  28.52054496479919,
  25.138058996097822,
  -12.172365356008507],
 'Indonesia': [-8.994275382081153,
  -9.506480650315009,
  20.80984931795944,
  -5.259419303030766,
  16.750605725105938,
  1.072126256948236,
  -26.116353210762433,
  26.868877941378845],
 'Panama': [-1.2892544573018028,
  -26.23110498671617,
  -38.40001770489402,
  94.09826542186399,
  22.110470972482954,
  2.433471200397541,
  -32.96098141265683,
  55.172257357548645],
 'Sudan': [10.356673254770477,
  36.463968023180215,
  3.915184374692804,
  -13.735028573062792,
  -7.797124564483282,
  -17.824467821714784,
  22.242911604586002,
  -29.91470053740737],
 'Venezuela': [-31.595763131842645,
  -54.54383071379858,
  -20.03170374352935,
  100.61170325077993,
  249.15571055647268,
  -1.3431543162543358,
  78.48276613059204,
  10.281103768898902],
 'Liberia': [-7.850935869377739,
  -18.271332026431296,
  12.390014130946758,
  52.52696251040159,
  -3.027030500531591,
  23.889472772407295,
  -20.072457848953274,
  35.669322947394846],
 'Kenya': [-9.73348610190855,
  5.5620040699481565,
  -3.9672905918030965,
  16.442109222493894,
  37.28033498689558,
  4.820065945521446,
  -1.082980226889485,
  4.134719076891669],
 'Saudi Arabia': [-3.810853608858089,
  14.175921339597707,
  -8.893860085407434,
  -13.213922006172407,
  -2.344318674910184,
  19.02849270822791,
  -23.924246941986695,
  -90.58484328621013],
 'Tajikistan': [-1.8261552928841462,
  -41.62242104181274,
  -9.137126686378894,
  3.7272553632538896,
  13.047313578084484,
  -17.02682698252367,
  10.924605961499822,
  34.739168107600534],
 'Afghanistan': [-19.601358333923034,
  -17.007264313420922,
  -9.948705262906598,
  18.279455386285015,
  -13.60891118734202,
  2.399495753809111,
  32.78730128808962,
  12.36693033281191],
 'Taiwan': [19.182289356148384,
  22.64588156119205,
  -19.293897647072633,
  46.437813749501046,
  32.52195510099332,
  -6.322886431579988,
  -8.181853055871635,
  -1.2915908255782815],
 'Tanzania': [6.2912984968755525,
  -22.280802116277187,
  -18.505836607003047,
  21.668454546323602,
  93.8605705587743,
  -1.5687451509363348,
  -11.391443566666837,
  14.327763660755743],
 'Thailand': [-6.229991730852758,
  -17.241321414638065,
  0.4129121391029056,
  -3.30681763242181,
  64.38022764526077,
  -7.717814742678275,
  -31.973305717853318,
  16.375560844919423],
 'Dominican Rep.': [43.985517823590904,
  -38.677579129164904,
  3.5096010010728262,
  77.42936961513041,
  46.534858645741785,
  12.9556122927446,
  0.9443139155873581,
  69.296846531209],
 'Argentina': [-51.1651740855667,
  -19.052737331873814,
  2.7301017079153667,
  28.700102664576164,
  15.172693929898706,
  -7.703186780943394,
  -13.728005756016815,
  34.756256047087234],
 'Guinea': [-49.255691486003926,
  0.8137061956043468,
  4.025528213539609,
  37.20408914807578,
  12.521375569199567,
  23.579085737257156,
  -0.5700461208523633,
  50.64523212327787],
 'Angola': [7.242244212885107,
  -22.93900323029495,
  -44.01327132438983,
  42.85640403632802,
  23.4756717311692,
  -7.942130527990865,
  -14.694642518371815,
  -1.4154071817479852],
 'Jamaica': [29.255711722264046,
  -60.70809410546438,
  -4.73588754841373,
  200.19024496924885,
  46.206692744350406,
  18.84614813877603,
  -16.441862564208254,
  115.37557550971367],
 'Cameroon': [7.877362045528025,
  -23.41596594723223,
  -22.786422000306995,
  45.625519441137506,
  54.949311572780026,
  -0.05275727059778079,
  1.4244850446994972,
  0.861797779891238],
 'Bahrain': [5.988777812088419,
  6.430243201270058,
  -12.933522258431163,
  21.159909675187173,
  34.41710295204079,
  -17.30942976897879,
  -24.32300852829301,
  -22.877295343151083],
 'Cayman Islands': [-69.68710809775884,
  9.723892018881998,
  -59.18263832810331,
  17.358456929773624,
  333.5287884934927,
  -56.037907469865644,
  -82.24367545878331,
  2023.9080622261354],
 'Latvia': [14.677239478818827,
  -13.336578877924998,
  15.438584259193533,
  -37.53551711879919,
  -0.8586214842273399,
  -1.017409251240864,
  -17.271882738518684,
  40.59261393282525],
 'Benin': [-24.137475014208356,
  -20.32893055082218,
  5.418715332546142,
  13.083940794842386,
  22.085211294516593,

In [27]:
#quick quantity check
len(countryExpchange.keys()) == len(data['Country'].unique()) == len(pdata['Country'].unique())

True

In [29]:
#selected countries with zero exports check
for state in ['Vatican City State', 'Pitcairn', 'Melilla']:
    listTotal = pdata[(pdata['Country'] == state)][['Year', 'Total']].sort_values(by = ['Year'], ascending = True)
    listTotal = listTotal['Total']
    listcountry = []
    for x in range(1,9):
        print(state, x, listTotal.iloc[x], listTotal.iloc[x-1])

Vatican City State 1 0.0 4.876
Vatican City State 2 17.968 0.0
Vatican City State 3 0.625 17.968
Vatican City State 4 0.0 0.625
Vatican City State 5 0.411 0.0
Vatican City State 6 298.9 0.411
Vatican City State 7 2.807 298.9
Vatican City State 8 0.0 2.807
Pitcairn 1 0.0 0.0
Pitcairn 2 0.0 0.0
Pitcairn 3 0.0 0.0
Pitcairn 4 0.0 0.0
Pitcairn 5 0.0 0.0
Pitcairn 6 0.305 0.0
Pitcairn 7 0.0 0.305
Pitcairn 8 0.0 0.0
Melilla 1 0.0 545.983
Melilla 2 0.0 0.0
Melilla 3 48.466 0.0
Melilla 4 0.0 48.466
Melilla 5 0.0 0.0
Melilla 6 0.0 0.0
Melilla 7 0.0 0.0
Melilla 8 0.0 0.0

In [30]:
generalderivlist = []
for state in countryExpchange:
    derivlist = []
    derivlist.append(state)
    for x in countryExpchange[state]:
        derivlist.append(x)
    #print(derivlist)
    generalderivlist.append(derivlist)
print(generalderivlist)
countryExpchange = pd.DataFrame(generalderivlist, columns = ['Country', '13/14', '14/15', '15/16', '16/17', '17/18', '18/19', '19/20', '20/21'])

[['Germany', 9.727399107701217, -10.967135545120854, 4.654996871675032, 7.856521731919908, 6.09578855840891, -4.242381435759935, -3.8426714287329578, 9.801693182710158], ['USA', 4.129094860908422, 1.4251025166786224, 3.4564001158114532, 27.501969972163387, -2.0176560466881543, -1.1253287769494635, 13.514147079083806, 29.70331947072078], ['United Kingdom', 11.940156168021176, 5.935226618758405, 10.5223978035623, -16.963636386533754, 15.518575815232062, -1.7022234857504648, -0.3815489255672766, 10.115708806242797], ['Italy', 0.1633410618922415, -4.457045107863367, 9.854011585745281, 11.839162150155103, 14.332165323093005, -2.9304418963054246, -17.127595885332493, 27.725646368698186], ['Iraq', 1.5771612801326995, -24.231746700490987, -14.754995491604427, 18.994070136432395, -6.655102323167195, 8.331932202337388, -10.576292885344662, 9.058993239776235], ['Spain', 9.290168555243028, -0.5842988098871293, 5.662559074158158, 25.9400918330007, 23.32868736585929, 0.2173098415005903, -17.880592630193682, 31.46256895921724], ['France', 3.0322844077008915, -11.012396557503191, 3.4091900280442955, 9.285569368799408, 11.02335730416415, 3.791696298816283, -9.444705685803623, 12.7118142740267], ['Netherlands', -3.4258112954879127, -8.249359199890039, 14.648093989895749, 9.016984755129531, 21.7272579434731, 12.962374067747318, -9.83702962148606, 18.788174824232318], ['Israel', 9.008142284748711, -8.384860189968446, 8.837297964443124, 14.739884946005045, 14.780337330545201, 10.960856584448408, 5.382557355533568, 20.417406116183344], ['Russia', -14.464336284158197, -40.29185063512779, -51.33582579986514, 60.0659041650728, 27.275176756785015, 13.676099948362562, 8.538820803023238, 15.085486965054962], ['UAE', -5.79441142089957, -0.09231998914435158, 12.300998616341928, 67.20677387914004, -64.88599605057568, 11.46945096395564, -22.033132481521456, 73.06795232678537], ['Romania', 12.84987748601063, -6.902893937928778, -4.2046613282589735, 18.326274883859426, 24.8016919469247, -1.5532528879066754, -4.397022351218938, 20.45576848720403], ['Belgium', 12.522476717191022, -14.613438310728489, 0.13983886356756514, 23.31333127563473, 23.43767360164022, -18.21429247200924, 7.021974882101145, 23.388024476633042], ['Poland', 16.21700344814634, -2.584966401578659, 13.741668650219175, 15.76205307930405, 9.454304506825672, -1.1242279980782643, 0.7508854252175512, 22.398742664776705], ['Egypt', 3.1739146911965443, -5.6122398483672065, -12.83506648280075, -10.03731436758425, 26.17703253015906, 9.146617926307643, -10.619931139412342, 24.622501857875577], ['Bulgaria', -0.8811306661988372, -16.74424953791379, 41.146990550160844, 17.34827040646394, -3.5208373389037484, -5.280896600887863, -1.2662288687917078, 35.43838706228408], ['China', -20.9022684796637, -15.822050908750606, -4.882012769015143, 27.71187152620158, 1.3487016039251287, -11.452012269272249, 5.127818596499867, 17.861913540837413], ['Greece', 8.070023724785313, -10.797670299679506, -1.0832290556868407, 17.08937907231334, 34.73046685333703, -3.3440691056388694, -19.84047609891316, 56.25181057449862], ['Ukraine', -22.271019318454034, -36.35608635799883, 12.657577292742971, 10.165859681819, 14.887074893576457, 28.043551843444803, -3.0664631336757453, 26.576121096700067], ['Morocco', 10.45547597096046, -5.257415927293185, 8.63194539157881, 13.217577614932496, 20.72598848761107, 15.278218341162209, -12.364830974623208, 27.18506141915573], ['Iran', -7.041912344597323, -0.6563562656474842, 32.73101973184887, -29.321538423241368, -28.356022408791194, -1.034891294040008, -17.686488336588702, 12.588259380373291], ['Libya', -30.832058261896165, -29.967821004598726, -35.437593728470596, -6.505681241795225, 72.9250622087599, 30.688268342473002, -20.12183365648672, 51.73370752681943], ['Azerbaijan', -3.568396627679815, -31.654439664664945, -33.66402155552821, 6.386420711873919, 15.265948101205652, 5.080676939685658, 16.603901339900062, 1.6948854164045901], ['Syria', 90.07757116072361, -19.21933872569097, -5.687032693405758, -0.22177803121280482, 0.6735499323761607, -3.2112518579623828, -7.805984878003736, 20.25977711123781], ['Uzbekistan', 4.142988767539313, -20.326928814887978, 7.964300224905796, 29.90467023275172, 41.813650877612815, 19.550996681525625, -6.330363644377613, 46.75760890504876], ['Slovenia', 8.602318002640352, 8.812429361458962, 14.593399893994995, 24.746377515491226, 28.072807533163413, 22.27758770218504, -10.951276766103978, -3.5176552053057475], ['Canada', 1.4208781112770907, -27.246305441581498, 8.451566318436242, 41.21121186585752, 21.722382403142237, -26.34759537564918, 1.969752137230052, 55.57132548423751], ['Sweden', 13.341275269945264, -11.358216564055535, 1.8825477055580686, 12.74952588648497, 4.831541603198386, -6.612764788037573, -7.126835944199527, 16.76224392543153], ['Algeria', 5.14188138400562, -13.39248410037741, -5.285817927809466, -0.11519010839126098, 16.0153925290623, -4.926627487968094, -28.1123999110261, 5.439154263817714], ['Georgia', 14.357487147066482, -21.924975622551955, 4.584879245930074, 1.6766513408526862, 7.536155444016601, 9.689575430854136, -7.398968159945063, 4.434762823531302], ['Czech Republic', 15.076081141686526, -6.955981820639289, 4.397905452996076, 10.562514571726854, 10.81310536939084, -4.277713876976319, 1.3576151388059454, 34.40897998608614], ['Lebanon', -54.88426178270457, -11.293597969831904, 4.617066599749697, 19.5732287896351, 0.44179978862761704, 15.342038422660353, -16.267184571648585, 58.70552437656937], ['Austria', 6.479272268739278, -9.414355528596975, 2.4695853438226667, 7.1455773053947125, 5.102830203418729, -1.8217342142130333, -4.520332067113387, 22.418101653454748], ['Portugal', -8.385831153626789, -0.7704128841948932, 16.741345311973266, 24.21284113590083, 37.03681779653847, -0.00021263841017971075, -19.39305386656064, 46.537488933672535], ['Serbia', 14.096907734042974, 0.35338267051900907, 19.712094029823035, 22.874772906381025, 20.333595412911443, 4.204766237521662, 6.69854462158177, 32.700068131375915], ['Hungary', 9.109732294367623, 3.4676309848513, 18.2218228427087, 27.27962743779284, 8.849031153192133, 8.409385610708075, -11.227436601963669, 3.066923514452813], ['Tunisia', -7.377939108296749, -10.94955749689247, 10.479196143745995, 0.24024800610082941, 2.071854430658715, -7.586609082483376, 4.66390297574395, 34.184914493702266], ['Kazakhstan', -5.954200527945474, -18.828111215796163, -19.098068903469134, 17.722858970214574, -5.952105437511146, 13.896367839472145, 9.495305220231032, 19.791769076288368], ['Denmark', 7.978034454102434, -15.731532401248337, 5.326131282951829, 6.8574644538785146, 6.068822000546303, -6.868874897988563, 0.5020059377176311, 12.193113232307118], ['Switzerland', 191.90471673605253, 76.23545956122241, -52.07058287226127, -66.3463647566422, 93.44750668314379, -41.61076153496235, 5.204232788992269, 2.5239535289158566], ['Turkish Rep. of Nor.Cyprus', 5.088364967026315, -14.681143274334064, -11.001745993624557, 19.825506924769833, 10.704665417211379, 3.8898304185309485, -33.76416105256772, 28.92083668734793], ['India', 0.476800264951982, 12.859075189637338, -0.9720647518473791, 16.922854661527275, 46.19179411516012, -1.3303592907502826, -23.72535496876509, 24.10052458445735], ['Qatar', 43.67744491562979, 18.335054490905158, 12.379431930573826, 62.58986374057955, 57.32363746438003, 3.92900331267354, -19.796887028416066, 1.2125275490448173], ['Yemen', 6.48410209554493, -38.552354955404454, 35.99529333652776, 6.054745214641, 28.02123425815688, 30.94741927586515, -13.93584231071172, 23.573440201524566], ['Hong Kong', 2.7521975418512534, -21.016301522952585, 14.596188341070127, 58.88649580439535, 28.01697951972546, -10.67595702263404, 9.954569069060204, 20.74870578978809], ['Brazil', -15.159705317760718, -41.60716243651426, -28.4089083090998, 17.425835438532022, 26.290552330562143, -2.5301462070005165, 18.975163950269636, 63.59617523854819], ['Turkmenistan', 15.480949816243506, -16.876848914946795, -30.432687212872413, -18.360851297132484, -54.981077290041625, 47.99209894397269, 5.674922175887187, 16.562648430319538], ['Australia', -11.447556896889655, -2.3467848644344147, 24.481691641596214, -14.93961971943537, 25.13152815182771, -6.098622709245416, 9.937967130973014, 21.932367198276935], ['Norway', -10.071516944829884, -18.846040325684545, 24.852907042154214, -0.819714055675802, -7.540497973516624, 39.61905046563308, 0.5714622790129242, 17.712032391092137], ['South Korea', 2.695052333259418, 20.056776767131556, -10.198357589249419, 12.293292526813705, 58.08987519628577, -3.9344723086979116, 16.95372086287119, -22.71132084037476], ['Ireland', 24.17850748879282, -0.6889404524076048, 6.66761566900973, 7.327576482986253, 42.34523643714687, -19.572543491157614, 5.591296447603655, 28.25389951773436], ['Belarus', -10.204671101110574, -23.938060371618608, 71.18823798003979, 18.1702401987617, 3.90314468727766, 19.07154045417485, 10.98006904020512, 34.944556309136374], ['Rep. of South Africa', -11.633024908837019, -11.918724412624716, -18.994027451869734, 16.33730055243685, 12.55124941180048, 2.763800746806022, 0.784742897668389, 40.333431719704535], ['Singapore', 5.367030020244212, 14.228821485613953, -4.475527698460013, 64.99682175714811, -17.817737662581568, 29.514687246686734, -54.21699355074829, 131.52606287015428], ['Nigeria', 7.815627582097018, -26.334619901714305, -33.99663724583847, 37.26526152208562, 8.28075319349777, 61.63374505363846, 2.5134674997729034, 27.01293651198271], ['Mexico', 23.90776818840248, 8.38479822173197, 27.914524425879293, 0.38990421693188004, 36.58017244629674, 2.463506182414199, -19.416790377436932, 38.15844627702136], ['Albania', 1.9906123958789212, -10.437308025935721, 6.359482795097282, 29.172227780485915, 6.558901974565456, 13.316372219481632, -2.437942274748184, 48.462848951614724], ['Jordan', 22.938712640966475, -8.325440050571153, -13.922312199127607, -5.497527087386544, 25.908533790081666, -24.991740636495553, -12.28154586523289, 19.881867081006565], ['Pakistan', 22.638816588823275, -36.2450642673426, 24.133795977442695, 0.8621281779264356, 34.9994073526851, 8.053663429443446, 12.723298662484916, 8.352020347356138], ['Kyrgyzstan', 8.145538051576985, -32.14702970463171, 3.348847017111156, 15.625196548311827, 3.393543388065079, 12.784396199318238, -5.546284418884239, 58.72798461880022], ['Malta', 7.994671426486288, -48.165722602721125, -54.139095741009, 125.4148031228044, 3.7216492070560436, 65.8928909770384, -54.73374600599049, 46.39164336957744], ['Kuwait', 18.704973951809723, 23.06804767393038, -11.842961032586652, 3.5759111931477516, 20.087189334069787, 1.4445884220203764, -0.2513746200108691, 11.633834757596917], ['Slovakia', 14.176865604896992, 5.457442503567966, -27.347778674111723, 0.12183630176301197, 36.31905341225965, 8.36594276493885, -8.167349447756934, 8.94492925859911], ['Bosnia and Herzegovina', 16.747955549020578, -9.092438826468264, 7.300076137671718, 12.186225636320236, 20.927886040091504, 5.232330126137219, -1.5238157833987076, 30.643610501665197], ['Chile', -10.006706071855698, -5.63452418764403, 15.934027748480162, 18.701423683512886, 50.96502565694168, -10.446790456003875, -21.446754489465125, 103.0991189884932], ['Peru', 4.381163121519482, -31.385543588982788, -55.717225206708164, 25.62085005928447, 57.22777764507641, 3.915374061656718, 27.970834654335764, 132.7603081598473], ['North Macedonia', 17.310141158117375, -4.9457463232204235, 17.248667393404805, -3.909247310191988, 8.600344910856418, -1.052607501345093, 1.7272688027925254, 22.76342381997065], ['Kosovo', -2.8605066872210205, -12.021516861937487, 8.628000688187655, 3.7207661832474592, 11.046711284644495, 10.954083628022882, 4.757646959659989, 37.26428368018744], ['Bangladesh', -7.644328494034203, 8.25232031401204, 25.356315347570014, 2.1774753194211405, 36.356070622289316, -9.951632844978775, -18.288462272602825, 42.417386208188375], ['Senegal', 36.32361710691077, -21.966929697390192, 22.392696732814343, 54.459263764009535, 57.57438231991554, -26.679386072081314, 25.01813355299134, 34.67625180134737], ['Finland', 9.708458970802836, -19.282502764466138, 9.785480685993807, 3.1630594594965755, 12.633659763700923, -2.5865457614348664, 10.591907061743244, 26.463664554856315], ['Oman', 26.952683641776986, -33.39843763776843, -24.743741515037588, -6.661898797877919, 89.71834675829659, 44.48190887141838, -17.209836573508873, -12.739043630630098], ['Croatia', 13.87511316681267, -14.2662862544229, 9.686121871307174, 13.154746262372786, 29.811780836945868, 6.551300121208281, -11.621334233576896, 15.032959567203296], ['Japan', -8.791199915263903, -10.389743332997858, 5.302118792709187, 15.916473870914437, 18.59394286666596, 1.8349759871549631, -12.251864892379293, -1.8583100821292442], ['Ghana', 0.19677691796211594, 25.695783551422014, 28.840831430683767, -24.35788699483965, 22.082883692741675, 33.702346205630775, 27.566027173251626, -13.292712751776447], ['Moldova', 7.4804735531802, -30.28581589454914, 25.12694685919925, 9.702133549421287, -5.262226283779404, 18.381781947150234, -2.4166933773929977, 20.56834752360015], ['Malaysia', 15.262985630744218, 12.468027068232956, -9.774042552756523, -10.915980142459647, 28.082643803718543, -5.708198024292798, 7.812306455409446, 4.540513089520504], ['Mauritania', -9.677254302110471, 4.016019556734451, -21.075632664051714, 13.001917210211356, 63.49891824737857, 15.841601758977575, -28.8956235773528, 231.47910646002114], ['Colombia', 34.08931425527308, 2.4526801549125343, -0.19614346990703968, 0.6936154869531252, 30.199418009875558, 3.515353525197762, -15.408570748100182, 81.645354344868], ["Côte d'Ivoir", 6.398231736498938, 28.385067843272573, -2.372259709111646, 29.708860116560842, 16.041738256278904, 27.047518105336188, 35.2443343021799, 18.516112483571924], ['Lithuania', -11.747612079137248, -14.909621609551094, -9.471285281636622, 13.58184585733262, -8.588305263117736, -12.05749919869098, 18.401996097868345, 9.189399305090596], ['Somalia', 4.063567923206302, 13.849029881581764, 65.28497443605292, 22.9699601031643, 24.721072541310086, 39.477536250480696, 5.914590898237737, 15.442912356836413], ['Vietnam', 55.597193201804586, -7.961031413650832, 49.83940719926516, 2.27275574806447, 29.543105283804284, 9.425958476456175, -30.47464290097611, 24.611884216465185], ['Ethiopia', -9.446827490922038, 17.019622338737882, 4.637100886414336, -15.631153945580733, -5.34173091283463, 15.880756067584102, -39.25676871920704, 30.2436573115054], ['Djibouti', -13.85639084557294, 62.14836849799037, -16.936043772206933, 26.352415160096587, 90.44808333736418, 28.52054496479919, 25.138058996097822, -12.172365356008507], ['Indonesia', -8.994275382081153, -9.506480650315009, 20.80984931795944, -5.259419303030766, 16.750605725105938, 1.072126256948236, -26.116353210762433, 26.868877941378845], ['Panama', -1.2892544573018028, -26.23110498671617, -38.40001770489402, 94.09826542186399, 22.110470972482954, 2.433471200397541, -32.96098141265683, 55.172257357548645], ['Sudan', 10.356673254770477, 36.463968023180215, 3.915184374692804, -13.735028573062792, -7.797124564483282, -17.824467821714784, 22.242911604586002, -29.91470053740737], ['Venezuela', -31.595763131842645, -54.54383071379858, -20.03170374352935, 100.61170325077993, 249.15571055647268, -1.3431543162543358, 78.48276613059204, 10.281103768898902], ['Liberia', -7.850935869377739, -18.271332026431296, 12.390014130946758, 52.52696251040159, -3.027030500531591, 23.889472772407295, -20.072457848953274, 35.669322947394846], ['Kenya', -9.73348610190855, 5.5620040699481565, -3.9672905918030965, 16.442109222493894, 37.28033498689558, 4.820065945521446, -1.082980226889485, 4.134719076891669], ['Saudi Arabia', -3.810853608858089, 14.175921339597707, -8.893860085407434, -13.213922006172407, -2.344318674910184, 19.02849270822791, -23.924246941986695, -90.58484328621013], ['Tajikistan', -1.8261552928841462, -41.62242104181274, -9.137126686378894, 3.7272553632538896, 13.047313578084484, -17.02682698252367, 10.924605961499822, 34.739168107600534], ['Afghanistan', -19.601358333923034, -17.007264313420922, -9.948705262906598, 18.279455386285015, -13.60891118734202, 2.399495753809111, 32.78730128808962, 12.36693033281191], ['Taiwan', 19.182289356148384, 22.64588156119205, -19.293897647072633, 46.437813749501046, 32.52195510099332, -6.322886431579988, -8.181853055871635, -1.2915908255782815], ['Tanzania', 6.2912984968755525, -22.280802116277187, -18.505836607003047, 21.668454546323602, 93.8605705587743, -1.5687451509363348, -11.391443566666837, 14.327763660755743], ['Thailand', -6.229991730852758, -17.241321414638065, 0.4129121391029056, -3.30681763242181, 64.38022764526077, -7.717814742678275, -31.973305717853318, 16.375560844919423], ['Dominican Rep.', 43.985517823590904, -38.677579129164904, 3.5096010010728262, 77.42936961513041, 46.534858645741785, 12.9556122927446, 0.9443139155873581, 69.296846531209], ['Argentina', -51.1651740855667, -19.052737331873814, 2.7301017079153667, 28.700102664576164, 15.172693929898706, -7.703186780943394, -13.728005756016815, 34.756256047087234], ['Guinea', -49.255691486003926, 0.8137061956043468, 4.025528213539609, 37.20408914807578, 12.521375569199567, 23.579085737257156, -0.5700461208523633, 50.64523212327787], ['Angola', 7.242244212885107, -22.93900323029495, -44.01327132438983, 42.85640403632802, 23.4756717311692, -7.942130527990865, -14.694642518371815, -1.4154071817479852], ['Jamaica', 29.255711722264046, -60.70809410546438, -4.73588754841373, 200.19024496924885, 46.206692744350406, 18.84614813877603, -16.441862564208254, 115.37557550971367], ['Cameroon', 7.877362045528025, -23.41596594723223, -22.786422000306995, 45.625519441137506, 54.949311572780026, -0.05275727059778079, 1.4244850446994972, 0.861797779891238], ['Bahrain', 5.988777812088419, 6.430243201270058, -12.933522258431163, 21.159909675187173, 34.41710295204079, -17.30942976897879, -24.32300852829301, -22.877295343151083], ['Cayman Islands', -69.68710809775884, 9.723892018881998, -59.18263832810331, 17.358456929773624, 333.5287884934927, -56.037907469865644, -82.24367545878331, 2023.9080622261354], ['Latvia', 14.677239478818827, -13.336578877924998, 15.438584259193533, -37.53551711879919, -0.8586214842273399, -1.017409251240864, -17.271882738518684, 40.59261393282525], ['Benin', -24.137475014208356, -20.32893055082218, 5.418715332546142, 13.083940794842386, 22.085211294516593, 12.137290730340489, -9.998982127853939, 17.837371390944632], ['Marshall Islands', 72.672608137591, -60.70242526801477, 73.51691930134858, 9.944330009050994, 4.098121611890071, 6.961457669874838, 89.33044555100491, -59.27833390634394], ['Haiti', 27.970407700496615, -38.376891447742715, -2.8791026448203527, 291.91940673064795, 16.472310637221412, 28.744851814953943, 24.40257632919667, -21.207130892035487], ['Countries and territories not specified', 26.36745535742544, -31.051460339601633, 25.856854617933188, -6.863277396811429, 27.082419538162526, 9.23892260231507, 12.921698319898534, 44.76858680341069], ['Sierra Leone', -2.6846916154100064, -3.6938091526999117, -9.85169614523257, 29.248386863237407, 5.068199575350696, 11.075108246471377, 26.49907544378085, 59.152133446677894], ['Estonia', -11.08847619664568, -32.92821732033902, 49.22470461049016, -36.80909005444434, -15.620283032304293, -5.850805344655652, -12.398960584243145, 48.38660245427258], ['New Zealand', 22.8461290732769, 2.254262433673704, 6.97958519380093, 8.108612798366455, 6.527874604552197, 0.12832622360856583, -7.111618524783358, 11.423548936654315], ['Guatemala', 4.709250301382539, 18.245002402099587, 26.275143769619234, 24.534000981030157, 17.53891344121992, 18.222465796177502, 1.5529030527116072, 107.4543322512215], ['Togo', -37.77110950638687, -3.2317301150988187, -36.73055860235167, 64.7384243659139, 32.45783006887613, 26.445467912799092, 42.374689305351154, -22.577511966757736], ['Montenegro', 9.066231667084622, 10.448895900735833, 32.794918509664406, 16.128878141702806, 31.042099219390895, 63.64823494976972, -21.6412

In [31]:
countryExpchange

,Country,13/14,14/15,15/16,16/17,17/18,18/19,19/20,20/21
0,Germany,9.727399,-10.967136,4.654997,7.856522,6.095789,-4.242381,-3.842671,9.801693
1,USA,4.129095,1.425103,3.456400,27.501970,-2.017656,-1.125329,13.514147,29.703319
2,United Kingdom,11.940156,5.935227,10.522398,-16.963636,15.518576,-1.702223,-0.381549,10.115709
3,Italy,0.163341,-4.457045,9.854012,11.839162,14.332165,-2.930442,-17.127596,27.725646
4,Iraq,1.577161,-24.231747,-14.754995,18.994070,-6.655102,8.331932,-10.576293,9.058993
...,...,...,...,...,...,...,...,...,...
232,Vatican City State,-100.000000,NaN,-96.521594,-100.000000,NaN,72625.060827,-99.060890,-100.000000
233,Pitcairn,NaN,NaN,NaN,NaN,NaN,NaN,-100.000000,NaN
234,Melilla,-100.000000,NaN,NaN,-100.000000,NaN,NaN,NaN,NaN
235,Bouvet Islands,NaN,NaN,NaN,-100.000000,NaN,NaN,NaN,NaN
236,Saint Barthelemy,NaN,-100.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
#check
len(data['Country'].unique()) == len(countryExpchange)

True

In [37]:
countryExpchange.to_excel(r'Exports_change.xls', index = False)