In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_excel(r'original Imports by Countries preformatting.xls')

In [3]:
data.shape

(1990, 15)

In [4]:
data.dtypes

Year           int64
Country       object
Total        float64
January       object
February      object
March         object
April         object
May           object
June          object
July          object
August        object
September     object
October       object
November      object
December      object
dtype: object

In [5]:
data.head(5)

,Year,Country,Total,January,February,March,April,May,June,July,August,September,October,November,December
0,2021,France,7.174425e+06,683689,695964,883884,679106,725461,572717,536576,589425,598116,576934,632554,NaN
1,2021,Netherlands,4.012335e+06,310284,422329,434602,455078,310983,381542,391312,319655,288144,285761,412646,NaN
2,2021,Germany,1.974191e+07,1.51078e+06,1.70141e+06,2.23174e+06,2.1294e+06,1.78322e+06,1.91817e+06,1.62971e+06,1.74449e+06,1.7178e+06,1.50929e+06,1.8659e+06,NaN
3,2021,Italy,1.042948e+07,671459,930785,1.07653e+06,962694,932964,1.01048e+06,905380,958353,912886,944546,1.12339e+06,NaN
4,2021,United Kingdom,5.035830e+06,467703,436646,575358,535700,427568,462629,463070,438712,409160,390079,429205,NaN

In [6]:
data.sample(15)

,Year,Country,Total,January,February,March,April,May,June,July,August,September,October,November,December
806,2018,Falkland Islands,4.034900e+01,-,12.346,-,-,-,-,-,28.003,-,-,-,-
17,2021,Austria,1.660121e+06,101234,156535,170716,182971,153237,148583,144001,156327,148199,139349,158970,NaN
101,2021,Zambia,4.681926e+03,156.068,1.787,6.839,86.749,343.007,110.059,92.76,1160.31,1221.07,1125.36,377.917,NaN
1934,2013,Yemen,2.607870e+02,58.231,7.235,34.776,6.772,24.975,1.22,3.79,1.184,-,4.971,10.272,107.361
1777,2013,Luxembourg,1.420326e+05,11773.8,8594.6,11642.8,10787,12911.4,12477.8,16704.2,9713.32,10262.5,7836,13063.3,16265.7
400,2020,Vietnam,1.369194e+06,102963,99911,106433,84326.9,69724.8,115704,120731,140081,136893,125324,145332,121772
1388,2015,Cape Verde,3.074672e+03,-,-,607.575,7.492,-,-,-,30.696,-,898.001,906.568,624.34
1822,2013,Morocco,5.795081e+05,36578.6,34754.2,49076.5,44715.8,70461.2,50230.5,64093.7,38358.9,45664.9,54540.5,39846.5,51186.8
317,2020,Seychelles,9.045632e+03,22.254,1.106,4.223,396.178,698.629,1318.76,1328.39,676.729,-,741.503,917.037,2940.82
614,2019,Thailand,1.140700e+06,85399.4,74175.3,80956.1,119238,101632,89605.1,104985,85204.5,93973.3,108081,104648,92801.1
961,2017,St. Helena And Dep.,4.580000e-01,-,-,-,-,-,-,-,-,-,-,-,0.458
1962,2013,Papua New Guinea,1.823900e+01,-,-,-,6.217,2.966,-,0.78,-,-,-,0.466,7.81
1309,2016,French Polynesia,1.378000e+00,0.975,-,-,-,-,-,-,-,0.223,-,0.18,-
658,2018,Italy,1.079192e+07,889710,958467,1.12526e+06,1.04987e+06,1.12911e+06,931376,938327,735884,652449,792449,787841,801169
832,2018,Thailand,1.402015e+06,147875,113725,129179,136366,138346,133226,122597,100092,109270,98571.1,101131,71636.7

In [7]:
#data = data.rename({'Unnamed: 0' : 'Country code'}, axis = 1).to_excel(r'Imports_by_Countries_preformatting.xls')

In [8]:
calendar = list(data.columns)[3:]
calendar

['January',
 'February',
 'March',
 'April',
 'May',
 'June',
 'July',
 'August',
 'September',
 'October',
 'November',
 'December']

In [9]:
data[data.isin(['-']).any(axis=1)]

,Year,Country,Total,January,February,March,April,May,June,July,August,September,October,November,December
21,2021,Gibraltar,2012.908,610.076,-,26.73,0.066,1339.53,0.19,0.248,1.28,0.48,34.312,-,NaN
22,2021,Vatican City State,110.513,-,-,-,-,-,110.513,-,-,-,-,-,NaN
60,2021,South Sudan,30.383,-,-,-,-,-,0.01,23.287,7.081,0.005,-,-,NaN
66,2021,Cape Verde,909.776,747.194,162.249,0.284,-,-,-,-,-,0.049,-,-,NaN
68,2021,Gambia,141.869,-,0.002,-,0.085,22.661,47.246,69.87,0.005,-,-,2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1983,2013,Niue Island,257.490,26.105,21.541,0.592,0.119,4.275,19.23,7.165,27.4,7.385,-,142.149,1.529
1984,2013,Tokelau Islands,9.900,-,-,0.507,2.67,-,1.497,2.905,-,-,-,-,2.321
1985,2013,Antarctica,0.950,-,-,0.95,-,-,-,-,-,-,-,-,-
1986,2013,South Georgia and Sandwich. Isl.,0.941,-,-,-,0.941,-,-,-,-,-,-,-,-
1987,2013,Stores and Provinces,130.085,92.936,6.991,-,27.54,2.618,-,-,-,-,-,-,-

In [10]:
data.replace(to_replace = '-', value = 0, inplace = True)
data.sample(10)

,Year,Country,Total,January,February,March,April,May,June,July,August,September,October,November,December
1190,2016,Somalia,2180.401,0.000,631.369,484.260,30.600,336.887,439.571,0.000,0.000,0.290,59.626,0.000,197.798
1813,2013,Tajikistan,441750.020,44916.426,37043.845,38499.682,41213.926,43475.658,20946.873,41731.986,30985.126,42863.820,30714.519,39590.282,29767.877
304,2020,Congo,8704.220,36.966,1459.803,2718.935,126.936,160.545,76.513,216.799,234.581,242.053,35.847,0.000,3395.242
674,2018,Faroe Islands,257.383,64.167,93.111,0.000,0.000,95.828,0.000,1.446,0.157,0.000,2.674,0.000,0.000
1198,2016,Mauritius,4741.552,503.658,522.128,540.712,268.772,176.248,372.383,416.000,774.545,327.146,172.614,509.957,157.389
640,2019,Samoa,3.988,0.000,0.000,0.000,0.000,0.000,0.000,0.254,0.458,1.757,0.462,1.057,0.000
101,2021,Zambia,4681.926,156.068,1.787,6.839,86.749,343.007,110.059,92.760,1160.310,1221.066,1125.364,377.917,NaN
1047,2017,India,6116450.758,463016.969,439040.045,515735.661,471234.282,508502.919,492390.231,383445.780,428940.116,626254.101,579992.489,603834.188,604063.977
929,2017,Morocco,930871.097,69698.050,49088.247,81385.282,67039.442,92937.236,63289.394,92504.138,71035.023,51011.908,113945.128,81035.689,97901.560
784,2018,Dominica,102.010,39.195,0.000,7.713,0.327,0.000,0.000,0.277,24.331,29.017,0.000,1.150,0.000

In [11]:
#data.to_excel(r'Imports by Countries formatting.xls', index = False)
data.sort_values(by = ['Year', 'Total'], ascending = False).to_excel(r'Imports by Countries formatting.xls', index = False)
data = pd.read_excel(r'Imports by Countries formatting.xls')
data.head(10)

,Year,Country,Total,January,February,March,April,May,June,July,August,September,October,November,December
0,2021,China,2.909954e+07,2199271.229,2240792.329,2812001.829,2400668.437,2632701.132,2857104.112,2656869.092,2839869.777,2896817.601,2525192.958,3038255.337,NaN
1,2021,Russia,2.557583e+07,1828695.485,1698792.238,2536611.244,2184414.521,2062000.491,2321161.609,2453197.621,2676074.221,2416633.221,2433916.714,2964329.523,NaN
2,2021,Confidential Country,2.039128e+07,1217767.439,1321487.151,1641839.736,1413209.230,1461216.047,1496559.702,1754070.914,1694832.065,1783197.771,2864147.550,3742951.524,NaN
3,2021,Germany,1.974191e+07,1510782.642,1701408.433,2231736.528,2129398.840,1783216.887,1918168.483,1629709.561,1744493.226,1717802.161,1509292.677,1865902.751,NaN
4,2021,USA,1.170375e+07,729148.527,850262.043,1070479.626,1099024.448,951362.329,1247350.441,937181.814,1160467.158,1412063.687,1057650.561,1188756.198,NaN
5,2021,Italy,1.042948e+07,671458.674,930785.440,1076533.293,962694.310,932964.194,1010483.114,905380.380,958352.675,912885.893,944545.700,1123391.436,NaN
6,2021,India,7.197060e+06,392163.726,386792.861,568903.228,593268.626,671614.002,650692.096,615242.088,939413.864,918982.198,652299.312,807688.403,NaN
7,2021,France,7.174425e+06,683688.813,695963.871,883883.549,679106.044,725461.310,572716.908,536575.725,589424.658,598116.352,576934.312,632553.527,NaN
8,2021,South Korea,6.869902e+06,493350.075,423998.462,563838.676,633714.549,677028.352,862785.679,638066.237,589371.076,649661.108,644437.194,693650.954,NaN
9,2021,Spain,5.699298e+06,400563.488,559853.080,602949.018,553414.175,469362.554,492291.091,383702.243,529290.145,539635.331,518356.493,649880.540,NaN

In [12]:
data.shape

(1990, 15)

In [13]:
countries = [state for state in data['Country'].unique()]
years = [x for x in range(2013, 2022)]
years_change = ['13/14', '14/15', '15/16', '16/17', '17/18', '18/19', '19/20', '20/21']
dfGDPchange = pd.DataFrame(columns = ['Country', '13/14', '14/15', '15/16', '16/17', '17/18', '18/19', '19/20', '20/21'])

In [14]:
#data = data.drop(columns = 'Country code')
data.columns

Index(['Year', 'Country', 'Total', 'January', 'February', 'March', 'April',
       'May', 'June', 'July', 'August', 'September', 'October', 'November',
       'December'],
      dtype='object')

In [15]:
pdata = data

keylist = ['Year', 'Country', 'Total'] + calendar
dict_country = {}
for i in keylist:
    dict_country[i] = None

for state in countries:
    for y in years:
        if state not in pdata[pdata['Year'] == y]['Country'].unique():
            dict_country['Year'] = y
            dict_country['Country'] = state
            dict_country['Total'] = 0
            for m in calendar:
                dict_country[m] = 0
            #print(dict_country, '\n')
            pdata = pdata.append(dict_country, ignore_index = True)
pdata.tail()

,Year,Country,Total,January,February,March,April,May,June,July,August,September,October,November,December
2137,2017,Stores and Provinces,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2138,2018,Stores and Provinces,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2139,2019,Stores and Provinces,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2140,2020,Stores and Provinces,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2141,2021,Stores and Provinces,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
pdata = pdata.sort_values(by = ['Year', 'Total'], ascending = False)
pdata[pdata['Country'] == 'Melilla']

,Year,Country,Total,January,February,March,April,May,June,July,August,September,October,November,December
2118,2021,Melilla,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.000
2117,2020,Melilla,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.000
2116,2019,Melilla,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.000
2115,2018,Melilla,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.000
2114,2017,Melilla,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.000
1319,2016,Melilla,0.734,0.0,0.356,0.378,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.000
1532,2015,Melilla,1.949,0.0,0.000,0.000,0.0,0.000,0.768,0.0,1.181,0.0,0.0,0.0,0.000
1754,2014,Melilla,2.163,0.0,0.000,1.328,0.0,0.167,0.000,0.0,0.000,0.0,0.0,0.0,0.668
1962,2013,Melilla,42.386,0.0,0.000,0.000,0.0,0.000,41.761,0.0,0.145,0.0,0.0,0.0,0.480

In [17]:
def country_absence():
    x = 0
    for state in countries:
        for y in years:
            if state not in data[data['Year'] == y]['Country'].unique():
                x += 1
    return x

In [18]:
#checking
print(data.shape)
print(pdata.shape)
print(pdata.shape[0] - data.shape[0] == pdata[pdata['Total'] == 0].shape[0])
print(pdata.shape[1] == data.shape[1] == pdata[pdata['Total'] == 0].shape[1])
print(country_absence())
print(pdata[pdata['Total'] == 0].shape)

(1990, 15)
(2142, 15)
True
True
152
(152, 15)

In [19]:
pdata.to_excel(r'Imports_by_Countries_formatting_filled.xls', index = False)

In [20]:
countryImpchange = {}
for state in countries:
    listTotal = pdata[(pdata['Country'] == state)][['Year', 'Total']].sort_values(by = ['Year'], ascending = True)
    listTotal = listTotal['Total']
    listcountry = []
    for x in range(1,9):
        if listTotal.iloc[x-1] != 0:
            listcountry.append(100*((listTotal.iloc[x]/listTotal.iloc[x-1]) -1))
        else:
            listcountry.append(None)
    countryImpchange[state] = listcountry

In [21]:
countryImpchange

{'China': [1.868962048683187,
  -1.7453583394412053,
  -1.7056826863337093,
  -4.421412673055403,
  -9.462306364201389,
  -11.056640683514185,
  20.457766286030534,
  26.292680978698947],
 'Russia': [-2.4373311505449857,
  -18.3681155085752,
  -25.437718573274527,
  29.932885278882182,
  13.005526960191638,
  1.781028720760891,
  -22.867720586192352,
  43.4482260183739],
 'Confidential Country': [1.9051809320499435,
  -28.425214664721533,
  -31.158825171016836,
  21.935959160324003,
  34.297496974967515,
  37.938450444909975,
  -9.799370325615875,
  49.247948542568196],
 'Germany': [-8.267306978638256,
  -3.178055209562336,
  -0.3884680352779668,
  -1.6168806222868204,
  -3.3487416443902185,
  -10.470402480280583,
  12.719449236114366,
  -9.160580214377456],
 'USA': [0.8577872384828877,
  -13.827308629769764,
  -2.8202913434986487,
  8.98054056356441,
  5.755389774789488,
  -8.836586203053177,
  -2.7214680251243073,
  1.551381387409223],
 'Italy': [-4.327802128238356,
  -12.378335361341875,
  -5.65609798414658,
  13.254898184094333,
  -10.955812291894773,
  -13.364870166400644,
  -1.6040878562247562,
  13.368577800058645],
 'India': [6.776276072437826,
  -22.200856058306307,
  1.1726292774199898,
  7.9815022068219665,
  23.02404565520415,
  -11.820906594342674,
  -27.204868124035585,
  49.003919559409596],
 'France': [-0.7618450243037755,
  -7.003407261740879,
  -3.8076835314517,
  9.713991971280645,
  -6.985814455440742,
  -13.736492800477828,
  3.372894620552036,
  2.6667052016540183],
 'South Korea': [21.606494593721415,
  -6.268999509585216,
  -10.743800143098326,
  5.4778604401378495,
  -2.699708325954453,
  -12.976178636432234,
  -0.7400679868825644,
  19.80433798511372],
 'Spain': [-4.993183211724428,
  -9.323852178569913,
  1.6507555355820047,
  12.601064507894266,
  -12.996464373124239,
  -21.761241837995925,
  13.344574616241589,
  13.094152614857046],
 'Belgium': [0.8430171404563591,
  -19.090250888692097,
  0.22206887949265397,
  18.836108967646716,
  -5.810649304001247,
  -11.437566951627097,
  15.074812396948944,
  41.37439501021878],
 'United Kingdom': [-5.876952433149651,
  -6.512015622996536,
  -5.393703902961189,
  24.204710513547955,
  12.210503985516974,
  -26.175841517901944,
  -0.9866431587476798,
  -9.795248140405466],
 'Netherlands': [3.020033886426532,
  -16.14662350532908,
  0.6075324888488387,
  26.35729728916667,
  -10.578728736916354,
  -7.130485675728615,
  13.287638260851242,
  10.57571055017823],
 'Ukraine': [-6.7638178577466785,
  -18.080540536430888,
  -26.221979455914923,
  13.079229442811592,
  -6.211678119709418,
  -1.0253404042384395,
  -4.955004233596472,
  53.25017501938096],
 'Japan': [-7.240097408880441,
  -6.1396960320443945,
  24.31878028995367,
  9.138490221719753,
  1.8275185520762571,
  -19.207475376108075,
  2.6154837765570926,
  5.609130121824957],
 'Brazil': [23.84188912160896,
  -1.2764306597149222,
  -2.8167687339442526,
  47.559946004128385,
  26.890478355343017,
  -19.63310153314337,
  21.58997480299414,
  9.704004667082655],
 'Poland': [-3.9975327283236273,
  -3.1920096448311286,
  6.995161228322488,
  7.0013522826751995,
  -10.39547468825176,
  -19.40102094288164,
  15.43709356016052,
  9.834570211277228],
 'Romania': [-4.742910204498796,
  -23.232170022908615,
  -12.106423406840872,
  8.685159405351994,
  4.794136845263974,
  1.8358143763147927,
  -0.05972237714186868,
  10.550250361619451],
 'Saudi Arabia': [22.431095393923183,
  -11.872142599133673,
  -14.091738857139614,
  20.679400657940207,
  13.210902748383724,
  -20.199449815552462,
  -14.24028890889064,
  76.19102333646725],
 'Switzerland': [-49.031636708196416,
  -49.38028623817613,
  1.6350821459659493,
  170.3821944879825,
  -58.47477575035879,
  17.003890743289894,
  130.25965304222993,
  -63.09829544998987],
 'Malaysia': [-4.878849993705481,
  9.480127633458002,
  45.27315547453159,
  51.36451831544262,
  -27.302353940837065,
  -17.931468634267322,
  7.69185563628989,
  36.56901245432061],
 'Iran': [-4.452383310700991,
  -38.84504024187774,
  -22.093225262660997,
  58.478004276372666,
  -7.45613198463494,
  -48.751965819026786,
  -66.94439721338028,
  109.6858578717348],
 'Czech Republic': [-8.77794414536961,
  -8.166653221056341,
  15.266091100915213,
  9.8463363779965,
  -6.060284707306107,
  -14.875918767171559,
  17.444668853998934,
  -10.595986581595906],
 'Bulgaria': [4.054963813475809,
  -19.70876845777002,
  -7.898348501712094,
  29.062261750070295,
  -8.79352893239087,
  -6.322631392157307,
  -10.932916007517758,
  10.239595520694111],
 'UAE': [-35.90399637384476,
  -39.52638743478998,
  78.44558724387471,
  48.58549051735086,
  -31.819634639338013,
  15.19116218766281,
  27.67842155681266,
  -60.76623096128249],
 'Egypt': [-10.67306122607592,
  -14.46613462924915,
  10.0464419344368,
  39.36368044362337,
  7.672240139057518,
  -12.20548692069775,
  -9.499976653594256,
  14.388894244451444],
 'Israel': [13.240531270043366,
  -37.55027400487878,
  -25.50356247542993,
  16.67948490045781,
  20.370979002865685,
  -20.00728541126825,
  -6.5315270146967475,
  25.387950493083423],
 'Greece': [7.3207394016156835,
  -57.64503986484968,
  -30.34970688462422,
  44.556792724415864,
  10.479552821013872,
  -28.37595243069222,
  -10.442273576650496,
  41.008499754675334],
 'Sweden': [-1.1788036011818437,
  -19.524201520983542,
  -7.48054970092249,
  17.034960217179183,
  -1.2553189425380196,
  -11.446748740275758,
  11.753453647408453,
  1.321389893460978],
 'Taiwan': [6.996275953636477,
  -5.046600122091959,
  -17.37376504661443,
  23.921014012383978,
  -15.02303773591932,
  -25.726941838177975,
  12.464738599745662,
  17.502236790565284],
 'Indonesia': [-2.3632215683214497,
  -21.851163012682573,
  -12.273207500315364,
  4.276811286987581,
  -8.966235477741503,
  -0.6671501549141867,
  -12.38513722782667,
  40.89334981252972],
 'Austria': [2.7221606445407165,
  -14.21625400083496,
  -3.54913191885321,
  -2.4132220717551056,
  3.1856316168835663,
  -13.823173909862218,
  7.644478276642008,
  13.316770584522075],
 'Uzbekistan': [-0.7766618532143776,
  -14.61672630719807,
  0.09364660033273076,
  15.894690632390729,
  3.7257673392612656,
  31.116279544294766,
  -14.92837256966869,
  69.6767306422582],
 'Iraq': [75.85645843983329,
  16.07730242041616,
  172.29889179551253,
  79.79115431747921,
  1.3814567496463814,
  64.18684776112364,
  206.2382556700287,
  -80.64146938231285],
 'Thailand': [-4.858597506177231,
  -10.281412437181315,
  18.422754529280596,
  26.180523383667275,
  -26.469570438412337,
  -18.638535747661912,
  6.128645003367539,
  22.58421057269089],
 'Hungary': [-3.4562942644121297,
  11.300493362194008,
  -0.04828890370540684,
  15.6133568640352,
  -4.509069836145563,
  -13.865155620528558,
  12.429860376252844,
  -0.33698670455920565],
 'Kazakhstan': [-30.462257654955227,
  -8.812771264331909,
  1.5513124641221898,
  31.92473154105113,
  7.222030775203603,
  -12.344672315243589,
  -15.912695373865516,
  23.227023217837562],
 'Colombia': [14.875713611191843,
  -2.009574496389177,
  21.67417437264023,
  61.74909676105334,
  20.66690542826848,
  -23.95987215697715,
  -29.54521311066537,
  41.71232027341585],
 'Vietnam': [23.086722785722703,
  -7.85889499755148,
  -7.271259928328644,
  51.336536661965646,
  -28.649170451407112,
  -17.87119996158848,
  -13.046180808618956,
  3.064798298684379],
 'Finland': [-9.301936954633783,
  -14.943650346371351,
  -5.756772816385913,
  1.155399368539567,
  4.832758813304983,
  -9.798353297597174,
  10.73581168662594,
  19.8993000563239],
 'Rep. of South Africa': [-20.969554899038645,
  -21.91492344076019,
  16.465514953909487,
  63.25216114352161,
  -19.541258821294715,
  -45.41379756738553,
  17.724661816545506,
  21.836243200561256],
 'Algeria': [29.963296998219093,
  -19.52133060559973,
  -36.806019831122015,
  69.43561419099493,
  45.420520049014335,
  -37.91399682703316,
  -21.116385082644808,
  86.84635332211015],
 'Portugal': [14.222602683537167,
  -14.553222935205435,
  3.174617878151831,
  0.9654966168994195,
  6.267305338642171,
  17.049874669013,
  6.2996908334803425,
  7.0337646358594075],
 'Slovakia': [-15.564185228883233,
  -5.579280787491314,
  9.246299821962033,
  -5.60989220760677,
  -12.988297751993837,
  -3.3682117520555166,
  26.803663095390927,
  -2.4907323931045555],
 'Denmark': [24.88759512711425,
  -22.71367258953173,
  12.245200999756168,
  -10.099818707309115,
  2.296598744307987,
  12.356724397017604,
  -12.38160309355597,
  12.045811072086487],
 'Oman': [-32.07732036055939,
  -46.188362664561375,
  -20.420995817519927,
  102.34537913946684,
  -28.534968068260834,
  225.77855096687628,
  45.46903537044551,
  186.47892007033238],
 'Canada': [-16.446215420657328,
  -18.542008163041224,
  16.320188499853018,
  95.15500679200616,
  -11.316876654857811,
  -17.692924428933686,
  -33.91318746377922,
  -12.964776563426861],
 'Ireland': [9.141619845106842,
  -7.052243879425657,
  -1.3723031033921473,
  17.10570138063183,
  -8.124026292569987,
  -9.095129074477592,
  11.0015523437464,
  -0.05557013040478065],
 'Mexico': [1.8605575542409492,
  -16.273251638649622,
  0.9611327653598734,
  -6.40704969198822,
  -19.75666992226858,
  10.292226543403915,
  12.319310422967543,
  4.84263414799333],
 'Australia': [-54.64352476013043,
  -0.8747555892971604,
  15.065980856914706,
  251.32802335001205,
  -51.76247130023934,
  -3.68756039748398,
  -60.677845146356326,
  110.65646562065731],
 'Norway': [-16.640664148520802,
  -23.29291367987055,
  -6.561774909001161,
  31.718383418413865,
  -6.37286626228205,
  1.0238856084305858,
  -12.09352279959175,
  17.41378550430701],
 'Morocco': [10.116681515352543,
  14.135362862323731,
  26.411668529108457,
  1.104283014239793,
  -19.115577717845934,
  -5.262642916910066,
  -9.982852976108326,
  23.824075724755247],
 'Libya': [-15.54110505448849,
  -11.290536359708314,
  -14.987079061969855,
  18.817021837432325,
  60.145912802781986,
  30.086352479259325,
  246.28548176301624,
  -56.92578636133043],
 'Azerbaijan': [-21.2350424099952,
  -26.002752363314606,
  -8.13483263759408,
  17.101898777732295,
  6.321120401033298,
  0.6350157576742843,
  -0.0757330107627352,
  60.676131168063876],
 'Turkmenistan': [-3.1587195227125275,
  -16.967603086398032,
  -19.35881337009715,
  -4.755847181371752,
  -22.11930432786279,
  -9.152469017471955,
  -7.36341058324097,
  93.30821726394736],
 'Qatar': [5.021193877129249,
  2.2026096667089323,
  -31.140571203311197,
  2.3370101900369145,
  33.02568359541675,
  -20.471203559490547,
  -2.9497088519369385,
  79.44022256086679],
 'Lithuania': [-18.011008933639605,
  -13.513540674590363,
  12.444699991777641,
  78.63700574678944,
  -20.395191588233295,
  -24.25103580258322,
  50.98897173227896,
  15.533355730041553],
 'Argentina': [-8.90527396796662,
  -23.711412964728883,
  57.10023478802353,
  14.336427375287286,
  -16.495488903870402,
  -5.658422112763006,
  8.28961116737139,
  -14.704295922357137],
 'Bangladesh': [1.2405782416479827,
  -4.703625772932385,
  -10.820436434793335,
  0.6280903954972938,
  -25.72979259548459,
  -10.170220369554372,
  12.042747363084727,
  -23.813274918957827],
 'Georgia': [14.003510949922426,
  -0.015565545467288722,
  -17.16095215817529,
  -3.5906671489017605,
  17.8017578434412,
  5.27590383871499,
  28.101020327366257,
  21.400608681020138],
 'Venezuela': [-36.78501168248187,
  -13.43222403482004,
  -41.63573778959139,
  85.0870247550221,
  774.7792322520303,
  -98.03894155070029,
  212.03373160885434,
  583.4551961620941],
 'Slovenia': [-1.2290183471593052,
  10.135289562615423,
  -13.209466156815386,
  29.244606862662657,
  -8.711464663649204,
  2.364428275780961,
  4.842506478509012,
  5.862237809388393],
 'Serbia': [28.096044958193733,
  -6.77249859301029,
  18.8561082834616,
  34.788116465164045,
  -20.14308224796646,
  11.171941815539622,
  -1.192374492197834,
  -7.002408127840765],
 'Singapore': [-4.038220123658021,
  8.685399932474791,
  -6.097220262157965,
  13.592439870852523,
  -12.722082906363763,
  -20.26178030004879,
  4.665155243344188,
  16.038925528163706],
 'Croatia': [-33.986966051037435,
  -0.8460343753180166,
  2.4358261540949666,
  52.1966012317221,
  -4.511727780247588,
  5.334628273100894,
  7.732313697643045,
  43.42850825045941],
 "Côte d'Ivoir": [100.94884624768285,
  6.6272482179994485,
  -21.46143821259139,
  11.302640427078202,
  -24.442884902828666,
  -6.300650134956087,
  75.73594130729555,
  4.426914808806193],
 'Chile': [-8.894105159784015,
  -21.414870414873675,
  -17.177508883482773,
  18.603149845332666,
  30.92627178066998,
  -35.412482737933026,
  17.500389214736643,
  13.974437020146313],
 'Moldova': [-0.20809237228528454,
  -15.472699071488849,
  -20.330386880978867,
  23.547627404516945,
  -9.067537176806773,
  33.136419110590886,
  -31.36629537347889,
  80.52004100666676],
 'Bahrain': [68.19776387902495,
  -63.398771327913,
  37.48819357611062,
  17.552778784721855,
  10.533909159301636,
  1.1680442926402579,
  -7.241293077034272,
  67.46666474074499],
 'Pakistan': [0.8165745367845201,
  -33.78480014513381,
  -5.850360890569995,
  27.78507432895927,
  -1.1517587093775372,
  -11.364071648751306,
  -12.24498611821735,
  4.769321166413643],
 'Mauritania': [338.1263030245348,
  -19.599351720641366,
  43.34537898299147,
  137.91621824074772,
  -33.59795668284371,
  185.32876562416004,
  -67.51086739845348,
  923.1149589356426],
 'Tunisia': [-27.74044202625592,
  -30.447375788870147,
  39.94192792744889,
  3.917326781558672,
  1.7731825460500117,
  -18.741359868222563,
  -20.78157839076087,
  65.48664331718793],
 'Peru': [-19.38570496114731,
  -11.70282320634718,
  -6.2295577332545875,
  27.58383489401186,
  42.061370202463344,
  -33.27947134704905,
  296.2540933053455,
  -17.687997423921598],
 'Uruguay': [-55.10394839215266,
  233.87836539376488,
  40.18150597118573,
  67.23374508840007,
  28.45674054223244,
  -38.973636434793335,
  -25.662825183191927,
  4.123168668753219],
 'Belarus': [-23.655892599407036,
  48.234868410512874,
  -53.779764089600555,
  81.70221061134653,
  -8.494176353484706,
  -2.1304281304752926,
  6.621846458883507,
  28.507814422882216],
 'Latvia': [0.6337341097803151,
  -28.244949135072172,
  61.06812673238275,
  -30.045190728399184,
  20.085773421867835,
  -0.003853640150996984,
  -6.712648851387071,
  34.09060247321803],
 'Bosnia and Herzegovina': [31.35860317070749,
  39.40114573365179,
  7.566137064358935,
  -3.8913401594043995,
  -10.594713210127615,
  -19.093203425839178,
  4.901118599648013,
  1.0148000759209408],
 'Estonia': [17.04079902043809,
  -9.756011724076185,
  -17.19146484776328,
  23.022361895776644,
  -21.63160455915203,
  -13.11238613442538,
  -14.986682164295084,
  22.94099013492188],
 'North Macedonia': [-1.9145779703067412,
  -0.5303167050704549,
  -2.4989418818065268,
  25.450680668904567,
  17.58707668272772,
  -9.704373749117368,
  21.516113284449688,
  38.80777059529845],
 'Syria': [35.37941414828298,
  -39.6554301724657,
  24.3048501590299,
  5.994521553372656,
  -9.11191320498136,
  13.260841823732129,
  109.72048241219485,
  -28.774660178491274],
 'Tajikistan': [-45.749293910614874,
  -6.999506639832543,
  -28.086761201010713,
  39.77551877931804,
  18.196061858000423,
  -25.197934062654546,
  -24.754603897983387,
  17.30221210436229],
 'Philippines': [-31.55633247192987,
  3.3958014130610836,
  -5.109512213987488,
  16.311023772299894,
  -15.384970359083338,
  7.89041936758581,
  -5.54383748220566,
  10.718050001409441],
 'Ecuador': [14.646740026194816,
  14.603606851678963,
  -11.909532661387479,
  18.901630687355198,
  -6.770032594540454,
  -21.813636868870457,
  -8.830156171572845,
  -12.803926051767],
 'Bolivia': [83.48101217025248,
  -71.90725913833288,
  1692.8529426337632,
  284.1017512697607,
  25.192154040086436,
  21.618841328561334,
  49.04557465992732,
  -20.346234728184264],
 'Luxembourg': [11.20293536071635,
  46.000717708361336,
  -38.91156182688075,
  -8.34461632156287,
  33.07506790079282,
  -33.32344253664894,
  21.98118012086494,
  -10.886389955249488],
 'Turkish Rep. of Nor.Cyprus': [17.79237201818864,
  -13.913016819148648,
  -5.037181107097377,
  3.3050987258868902,
  -3.0184660854946532,
  -30.140719485229017,
  28.202890159270734,
  41.80712088810947],
 'Ghana': [-13.72075152783504,
  9.543808309716173,
  9.588925748449405,
  -32.75317599765708,
  -36.81376398011995,
  31.70582391055612,
  187.5466338024408,
  -62.60584869304395],
 'Jordan': [78.35461813777415,
  -2.516590336161928,
  -30.237903530208975,
  8.255964728505628,
  -11.945626383028152,
  -52.54961123531745,
  92.39262344708006,
  6.523893034147998],
 'Chad': [39.79528145562019,
  30.902742935368323,
  3.3483635053675354,
  -5.364056680992324,
  13.710746334714496,
  40.53065836899212,
  100.18711753216331,
  41.46485332069594],
 'Malta': [-44.19743552016453,
  -36.69420412396413,
  46.75257328483846,
  58.722220946192614,
  -39.650737367154655,
  87.31158723760504,
  47.781432810250976,
  -11.24181350363842],
 'Nigeria': [-2.7975515027272135,
  25.271994347447936,
  -27.175397081334797,
  -0.7126435714709278,
  -1.2139459333245672,
  8.886996507690604,
  -17.332734404424667,
  -26.90962329553017],
 'Sudan': [-40.549772007148924,
  51.32985153392418,
  91.40833260239619,
  62.84477760681475,
  -6.038605341156211,
  -5.385978077915931,
  28.200362571062975,
  -11.936928798380542],
 'Sri Lanka': [7.599049685140824,
  -11.960342149054847,
  14.32373964506386,
  6.720071612235201,
  -9.011230799915747,
  3.6574386713610796,
  -11.40385860069303,
  1.923525932226955],
 'Kuwait': [-27.828937385745345,
  -11.855961284498907,
  -25.65299205349928,
  42.31867976378256,
  -8.628936398997578,
  -32.46796408939731,
  -63.635333576412776,
  68.34606500711897],
 'Kyrgyzstan': [12.352757443970974,
  -1.9133564118386626,
  11.880028286631216,
  17.799223687107713,
  -58.72290245858181,
  20.635258394027424,
  18.014347186693456,
  -19.410267587724483],
 'Hong Kong': [1.1486622518492196,
  -16.687589488911748,
  34.63278733827204,
  -17.81724614278336,
  41.31612612910707,
  73.99415920853514,
  -3.474546509065357,
  -74.96846233787473],
 'Cambodia': [51.01368629100502,
  -14.359360732060388,
  -18.98859174340589,
  -4.285292786933548,
  12.897863783267649,
  -9.1846499915483,
  -13.024729340564779,
  -6.916161286515388],
 'Albania': [19.710755352514898,
  -46.296780647709404,
  -63.987670714303604,
  30.20110630911985,
  -5.5216322601851715,
  -6.681062813678162,
  50.78332843725939,
  67.11528840149424],
 'Cameroon': [-10.080736498656485,
  -2.8198079122503827,
  21.14686213123116,
  15.084812950251592,
  -7.236616585237421,
  7.047064608759035,
  -16.047507219391875,
  23.720770048635465],
 'Mali': [1990.063232970186,
  -76.18336322186174,
  351.4184194621736,
  193.66951489994105,
  -32.744100479517854,
  -56.96781853647016,
  -56.0717898604127,
  1233.0059245154937],
 'Lebanon': [-27.41596096275486,
  -47.91077680813298,
  15.714905734791662,
  48.16469014922986,
  31.068808427971284,
  -63.465584749736756,
  -19.754880567041976,
  -9.165144093632305],
 'Costa Rica': [-18.62225950768185,
  -57.52548271283293,
  7.9521047283239055,
  -15.314116564727476,
  -29.329107308598434,
  25.95960904058481,
  16.79872574518504,
  -33.34367540731786],
 'Myanmar': [26.74499152707788,
  -9.115801643196676,
  7.688768177680294,
  171.03576768745307,
  51.674558873720635,
  24.720320592528466,
  -7.283116786845767,
  -13.44317351271378],
 'Mozambique': [9.654477902936808,
  3.2682968948172686,
  30.160059468472266,
  45.599476210207925,
  -36.511690607971836,
  -22.028639626580638,
  -2.3297835685978874,
  -43.49939782821796],
 'Tanzania': [-21.13601661337664,
  9.46693657451323,
  -38.70909386547696,
  76.14599767455086,
  -15.20537744674062,
  -27.293833115726162,
  66.98927251034392,
  -22.778840362637176],
 'Marshall Islands': [-67.75332133899371,
  3803.6013751371365,
  -48.31778326972081,
  202.92293136414133,
  -74.68362163007323,
  155.0257655270423,
  120.1121262075187,

In [22]:
#quick quantity check
len(countryImpchange.keys()) == len(data['Country'].unique()) == len(pdata['Country'].unique())

True

In [23]:
#selected countries with zero imports check
for state in ['Stores and Provinces', 'Ceuta', 'Tonga', 'Melilla']:
    listTotal = pdata[(pdata['Country'] == state)][['Year', 'Total']].sort_values(by = ['Year'], ascending = True)
    listTotal = listTotal['Total']
    listcountry = []
    for x in range(1,9):
        print(state, x, listTotal.iloc[x], listTotal.iloc[x-1])

Stores and Provinces 1 0.0 130.085
Stores and Provinces 2 0.0 0.0
Stores and Provinces 3 0.0 0.0
Stores and Provinces 4 0.0 0.0
Stores and Provinces 5 0.0 0.0
Stores and Provinces 6 0.0 0.0
Stores and Provinces 7 0.0 0.0
Stores and Provinces 8 0.0 0.0
Ceuta 1 4.586 44.933
Ceuta 2 1.992 4.586
Ceuta 3 19.514000000000003 1.992
Ceuta 4 0.0 19.514000000000003
Ceuta 5 0.0 0.0
Ceuta 6 0.0 0.0
Ceuta 7 0.0 0.0
Ceuta 8 0.0 0.0
Tonga 1 0.387 0.103
Tonga 2 0.0 0.387
Tonga 3 0.0 0.0
Tonga 4 0.0 0.0
Tonga 5 0.0 0.0
Tonga 6 0.0 0.0
Tonga 7 0.0 0.0
Tonga 8 0.0 0.0
Melilla 1 2.1630000000000003 42.386
Melilla 2 1.949 2.1630000000000003
Melilla 3 0.734 1.949
Melilla 4 0.0 0.734
Melilla 5 0.0 0.0
Melilla 6 0.0 0.0
Melilla 7 0.0 0.0
Melilla 8 0.0 0.0

In [24]:
generalderivlist = []
for state in countryImpchange:
    derivlist = []
    derivlist.append(state)
    for x in countryImpchange[state]:
        derivlist.append(x)
    #print(derivlist)
    generalderivlist.append(derivlist)
print(generalderivlist)
countryImpchange = pd.DataFrame(generalderivlist, columns = ['Country', '13/14', '14/15', '15/16', '16/17', '17/18', '18/19', '19/20', '20/21'])

[['China', 1.868962048683187, -1.7453583394412053, -1.7056826863337093, -4.421412673055403, -9.462306364201389, -11.056640683514185, 20.457766286030534, 26.292680978698947], ['Russia', -2.4373311505449857, -18.3681155085752, -25.437718573274527, 29.932885278882182, 13.005526960191638, 1.781028720760891, -22.867720586192352, 43.4482260183739], ['Confidential Country', 1.9051809320499435, -28.425214664721533, -31.158825171016836, 21.935959160324003, 34.297496974967515, 37.938450444909975, -9.799370325615875, 49.247948542568196], ['Germany', -8.267306978638256, -3.178055209562336, -0.3884680352779668, -1.6168806222868204, -3.3487416443902185, -10.470402480280583, 12.719449236114366, -9.160580214377456], ['USA', 0.8577872384828877, -13.827308629769764, -2.8202913434986487, 8.98054056356441, 5.755389774789488, -8.836586203053177, -2.7214680251243073, 1.551381387409223], ['Italy', -4.327802128238356, -12.378335361341875, -5.65609798414658, 13.254898184094333, -10.955812291894773, -13.364870166400644, -1.6040878562247562, 13.368577800058645], ['India', 6.776276072437826, -22.200856058306307, 1.1726292774199898, 7.9815022068219665, 23.02404565520415, -11.820906594342674, -27.204868124035585, 49.003919559409596], ['France', -0.7618450243037755, -7.003407261740879, -3.8076835314517, 9.713991971280645, -6.985814455440742, -13.736492800477828, 3.372894620552036, 2.6667052016540183], ['South Korea', 21.606494593721415, -6.268999509585216, -10.743800143098326, 5.4778604401378495, -2.699708325954453, -12.976178636432234, -0.7400679868825644, 19.80433798511372], ['Spain', -4.993183211724428, -9.323852178569913, 1.6507555355820047, 12.601064507894266, -12.996464373124239, -21.761241837995925, 13.344574616241589, 13.094152614857046], ['Belgium', 0.8430171404563591, -19.090250888692097, 0.22206887949265397, 18.836108967646716, -5.810649304001247, -11.437566951627097, 15.074812396948944, 41.37439501021878], ['United Kingdom', -5.876952433149651, -6.512015622996536, -5.393703902961189, 24.204710513547955, 12.210503985516974, -26.175841517901944, -0.9866431587476798, -9.795248140405466], ['Netherlands', 3.020033886426532, -16.14662350532908, 0.6075324888488387, 26.35729728916667, -10.578728736916354, -7.130485675728615, 13.287638260851242, 10.57571055017823], ['Ukraine', -6.7638178577466785, -18.080540536430888, -26.221979455914923, 13.079229442811592, -6.211678119709418, -1.0253404042384395, -4.955004233596472, 53.25017501938096], ['Japan', -7.240097408880441, -6.1396960320443945, 24.31878028995367, 9.138490221719753, 1.8275185520762571, -19.207475376108075, 2.6154837765570926, 5.609130121824957], ['Brazil', 23.84188912160896, -1.2764306597149222, -2.8167687339442526, 47.559946004128385, 26.890478355343017, -19.63310153314337, 21.58997480299414, 9.704004667082655], ['Poland', -3.9975327283236273, -3.1920096448311286, 6.995161228322488, 7.0013522826751995, -10.39547468825176, -19.40102094288164, 15.43709356016052, 9.834570211277228], ['Romania', -4.742910204498796, -23.232170022908615, -12.106423406840872, 8.685159405351994, 4.794136845263974, 1.8358143763147927, -0.05972237714186868, 10.550250361619451], ['Saudi Arabia', 22.431095393923183, -11.872142599133673, -14.091738857139614, 20.679400657940207, 13.210902748383724, -20.199449815552462, -14.24028890889064, 76.19102333646725], ['Switzerland', -49.031636708196416, -49.38028623817613, 1.6350821459659493, 170.3821944879825, -58.47477575035879, 17.003890743289894, 130.25965304222993, -63.09829544998987], ['Malaysia', -4.878849993705481, 9.480127633458002, 45.27315547453159, 51.36451831544262, -27.302353940837065, -17.931468634267322, 7.69185563628989, 36.56901245432061], ['Iran', -4.452383310700991, -38.84504024187774, -22.093225262660997, 58.478004276372666, -7.45613198463494, -48.751965819026786, -66.94439721338028, 109.6858578717348], ['Czech Republic', -8.77794414536961, -8.166653221056341, 15.266091100915213, 9.8463363779965, -6.060284707306107, -14.875918767171559, 17.444668853998934, -10.595986581595906], ['Bulgaria', 4.054963813475809, -19.70876845777002, -7.898348501712094, 29.062261750070295, -8.79352893239087, -6.322631392157307, -10.932916007517758, 10.239595520694111], ['UAE', -35.90399637384476, -39.52638743478998, 78.44558724387471, 48.58549051735086, -31.819634639338013, 15.19116218766281, 27.67842155681266, -60.76623096128249], ['Egypt', -10.67306122607592, -14.46613462924915, 10.0464419344368, 39.36368044362337, 7.672240139057518, -12.20548692069775, -9.499976653594256, 14.388894244451444], ['Israel', 13.240531270043366, -37.55027400487878, -25.50356247542993, 16.67948490045781, 20.370979002865685, -20.00728541126825, -6.5315270146967475, 25.387950493083423], ['Greece', 7.3207394016156835, -57.64503986484968, -30.34970688462422, 44.556792724415864, 10.479552821013872, -28.37595243069222, -10.442273576650496, 41.008499754675334], ['Sweden', -1.1788036011818437, -19.524201520983542, -7.48054970092249, 17.034960217179183, -1.2553189425380196, -11.446748740275758, 11.753453647408453, 1.321389893460978], ['Taiwan', 6.996275953636477, -5.046600122091959, -17.37376504661443, 23.921014012383978, -15.02303773591932, -25.726941838177975, 12.464738599745662, 17.502236790565284], ['Indonesia', -2.3632215683214497, -21.851163012682573, -12.273207500315364, 4.276811286987581, -8.966235477741503, -0.6671501549141867, -12.38513722782667, 40.89334981252972], ['Austria', 2.7221606445407165, -14.21625400083496, -3.54913191885321, -2.4132220717551056, 3.1856316168835663, -13.823173909862218, 7.644478276642008, 13.316770584522075], ['Uzbekistan', -0.7766618532143776, -14.61672630719807, 0.09364660033273076, 15.894690632390729, 3.7257673392612656, 31.116279544294766, -14.92837256966869, 69.6767306422582], ['Iraq', 75.85645843983329, 16.07730242041616, 172.29889179551253, 79.79115431747921, 1.3814567496463814, 64.18684776112364, 206.2382556700287, -80.64146938231285], ['Thailand', -4.858597506177231, -10.281412437181315, 18.422754529280596, 26.180523383667275, -26.469570438412337, -18.638535747661912, 6.128645003367539, 22.58421057269089], ['Hungary', -3.4562942644121297, 11.300493362194008, -0.04828890370540684, 15.6133568640352, -4.509069836145563, -13.865155620528558, 12.429860376252844, -0.33698670455920565], ['Kazakhstan', -30.462257654955227, -8.812771264331909, 1.5513124641221898, 31.92473154105113, 7.222030775203603, -12.344672315243589, -15.912695373865516, 23.227023217837562], ['Colombia', 14.875713611191843, -2.009574496389177, 21.67417437264023, 61.74909676105334, 20.66690542826848, -23.95987215697715, -29.54521311066537, 41.71232027341585], ['Vietnam', 23.086722785722703, -7.85889499755148, -7.271259928328644, 51.336536661965646, -28.649170451407112, -17.87119996158848, -13.046180808618956, 3.064798298684379], ['Finland', -9.301936954633783, -14.943650346371351, -5.756772816385913, 1.155399368539567, 4.832758813304983, -9.798353297597174, 10.73581168662594, 19.8993000563239], ['Rep. of South Africa', -20.969554899038645, -21.91492344076019, 16.465514953909487, 63.25216114352161, -19.541258821294715, -45.41379756738553, 17.724661816545506, 21.836243200561256], ['Algeria', 29.963296998219093, -19.52133060559973, -36.806019831122015, 69.43561419099493, 45.420520049014335, -37.91399682703316, -21.116385082644808, 86.84635332211015], ['Portugal', 14.222602683537167, -14.553222935205435, 3.174617878151831, 0.9654966168994195, 6.267305338642171, 17.049874669013, 6.2996908334803425, 7.0337646358594075], ['Slovakia', -15.564185228883233, -5.579280787491314, 9.246299821962033, -5.60989220760677, -12.988297751993837, -3.3682117520555166, 26.803663095390927, -2.4907323931045555], ['Denmark', 24.88759512711425, -22.71367258953173, 12.245200999756168, -10.099818707309115, 2.296598744307987, 12.356724397017604, -12.38160309355597, 12.045811072086487], ['Oman', -32.07732036055939, -46.188362664561375, -20.420995817519927, 102.34537913946684, -28.534968068260834, 225.77855096687628, 45.46903537044551, 186.47892007033238], ['Canada', -16.446215420657328, -18.542008163041224, 16.320188499853018, 95.15500679200616, -11.316876654857811, -17.692924428933686, -33.91318746377922, -12.964776563426861], ['Ireland', 9.141619845106842, -7.052243879425657, -1.3723031033921473, 17.10570138063183, -8.124026292569987, -9.095129074477592, 11.0015523437464, -0.05557013040478065], ['Mexico', 1.8605575542409492, -16.273251638649622, 0.9611327653598734, -6.40704969198822, -19.75666992226858, 10.292226543403915, 12.319310422967543, 4.84263414799333], ['Australia', -54.64352476013043, -0.8747555892971604, 15.065980856914706, 251.32802335001205, -51.76247130023934, -3.68756039748398, -60.677845146356326, 110.65646562065731], ['Norway', -16.640664148520802, -23.29291367987055, -6.561774909001161, 31.718383418413865, -6.37286626228205, 1.0238856084305858, -12.09352279959175, 17.41378550430701], ['Morocco', 10.116681515352543, 14.135362862323731, 26.411668529108457, 1.104283014239793, -19.115577717845934, -5.262642916910066, -9.982852976108326, 23.824075724755247], ['Libya', -15.54110505448849, -11.290536359708314, -14.987079061969855, 18.817021837432325, 60.145912802781986, 30.086352479259325, 246.28548176301624, -56.92578636133043], ['Azerbaijan', -21.2350424099952, -26.002752363314606, -8.13483263759408, 17.101898777732295, 6.321120401033298, 0.6350157576742843, -0.0757330107627352, 60.676131168063876], ['Turkmenistan', -3.1587195227125275, -16.967603086398032, -19.35881337009715, -4.755847181371752, -22.11930432786279, -9.152469017471955, -7.36341058324097, 93.30821726394736], ['Qatar', 5.021193877129249, 2.2026096667089323, -31.140571203311197, 2.3370101900369145, 33.02568359541675, -20.471203559490547, -2.9497088519369385, 79.44022256086679], ['Lithuania', -18.011008933639605, -13.513540674590363, 12.444699991777641, 78.63700574678944, -20.395191588233295, -24.25103580258322, 50.98897173227896, 15.533355730041553], ['Argentina', -8.90527396796662, -23.711412964728883, 57.10023478802353, 14.336427375287286, -16.495488903870402, -5.658422112763006, 8.28961116737139, -14.704295922357137], ['Bangladesh', 1.2405782416479827, -4.703625772932385, -10.820436434793335, 0.6280903954972938, -25.72979259548459, -10.170220369554372, 12.042747363084727, -23.813274918957827], ['Georgia', 14.003510949922426, -0.015565545467288722, -17.16095215817529, -3.5906671489017605, 17.8017578434412, 5.27590383871499, 28.101020327366257, 21.400608681020138], ['Venezuela', -36.78501168248187, -13.43222403482004, -41.63573778959139, 85.0870247550221, 774.7792322520303, -98.03894155070029, 212.03373160885434, 583.4551961620941], ['Slovenia', -1.2290183471593052, 10.135289562615423, -13.209466156815386, 29.244606862662657, -8.711464663649204, 2.364428275780961, 4.842506478509012, 5.862237809388393], ['Serbia', 28.096044958193733, -6.77249859301029, 18.8561082834616, 34.788116465164045, -20.14308224796646, 11.171941815539622, -1.192374492197834, -7.002408127840765], ['Singapore', -4.038220123658021, 8.685399932474791, -6.097220262157965, 13.592439870852523, -12.722082906363763, -20.26178030004879, 4.665155243344188, 16.038925528163706], ['Croatia', -33.986966051037435, -0.8460343753180166, 2.4358261540949666, 52.1966012317221, -4.511727780247588, 5.334628273100894, 7.732313697643045, 43.42850825045941], ["Côte d'Ivoir", 100.94884624768285, 6.6272482179994485, -21.46143821259139, 11.302640427078202, -24.442884902828666, -6.300650134956087, 75.73594130729555, 4.426914808806193], ['Chile', -8.894105159784015, -21.414870414873675, -17.177508883482773, 18.603149845332666, 30.92627178066998, -35.412482737933026, 17.500389214736643, 13.974437020146313], ['Moldova', -0.20809237228528454, -15.472699071488849, -20.330386880978867, 23.547627404516945, -9.067537176806773, 33.136419110590886, -31.36629537347889, 80.52004100666676], ['Bahrain', 68.19776387902495, -63.398771327913, 37.48819357611062, 17.552778784721855, 10.533909159301636, 1.1680442926402579, -7.241293077034272, 67.46666474074499], ['Pakistan', 0.8165745367845201, -33.78480014513381, -5.850360890569995, 27.78507432895927, -1.1517587093775372, -11.364071648751306, -12.24498611821735, 4.769321166413643], ['Mauritania', 338.1263030245348, -19.599351720641366, 43.34537898299147, 137.91621824074772, -33.59795668284371, 185.32876562416004, -67.51086739845348, 923.1149589356426], ['Tunisia', -27.74044202625592, -30.447375788870147, 39.94192792744889, 3.917326781558672, 1.7731825460500117, -18.741359868222563, -20.78157839076087, 65.48664331718793], ['Peru', -19.38570496114731, -11.70282320634718, -6.2295577332545875, 27.58383489401186, 42.061370202463344, -33.27947134704905, 296.2540933053455, -17.687997423921598], ['Uruguay', -55.10394839215266, 233.87836539376488, 40.18150597118573, 67.23374508840007, 28.45674054223244, -38.973636434793335, -25.662825183191927, 4.123168668753219], ['Belarus', -23.655892599407036, 48.234868410512874, -53.779764089600555, 81.70221061134653, -8.494176353484706, -2.1304281304752926, 6.621846458883507, 28.507814422882216], ['Latvia', 0.6337341097803151, -28.244949135072172, 61.06812673238275, -30.045190728399184, 20.085773421867835, -0.003853640150996984, -6.712648851387071, 34.09060247321803], ['Bosnia and Herzegovina', 31.35860317070749, 39.40114573365179, 7.566137064358935, -3.8913401594043995, -10.594713210127615, -19.093203425839178, 4.901118599648013, 1.0148000759209408], ['Estonia', 17.04079902043809, -9.756011724076185, -17.19146484776328, 23.022361895776644, -21.63160455915203, -13.11238613442538, -14.986682164295084, 22.94099013492188], ['North Macedonia', -1.9145779703067412, -0.5303167050704549, -2.4989418818065268, 25.450680668904567, 17.58707668272772, -9.704373749117368, 21.516113284449688, 38.80777059529845], ['Syria', 35.37941414828298, -39.6554301724657, 24.3048501590299, 5.994521553372656, -9.11191320498136, 13.260841823732129, 109.72048241219485, -28.774660178491274], ['Tajikistan', -45.749293910614874, -6.999506639832543, -28.086761201010713, 39.77551877931804, 18.196061858000423, -25.197934062654546, -24.754603897983387, 17.30221210436229], ['Philippines', -31.55633247192987, 3.3958014130610836, -5.109512213987488, 16.311023772299894, -15.384970359083338, 7.89041936758581, -5.54383748220566, 10.718050001409441], ['Ecuador', 14.646740026194816, 14.603606851678963, -11.909532661387479, 18.901630687355198, -6.770032594540454, -21.813636868870457, -8.830156171572845, -12.803926051767], ['Bolivia', 83.48101217025248, -71.90725913833288, 1692.8529426337632, 284.1017512697607, 25.192154040086436, 21.618841328561334, 49.04557465992732, -20.346234728184264], ['Luxembourg', 11.20293536071635, 46.000717708361336, -38.91156182688075, -8.34461632156287, 33.07506790079282, -33.32344253664894, 21.98118012086494, -10.886389955249488], ['Turkish Rep. of Nor.Cyprus', 17.79237201818864, -13.913016819148648, -5.037181107097377, 3.3050987258868902, -3.0184660854946532, -30.140719485229017, 28.202890159270734, 41.80712088810947], ['Ghana', -13.72075152783504, 9.543808309716173, 9.588925748449405, -32.75317599765708, -36.81376398011995, 31.70582391055612, 187.5466338024408, -62.60584869304395], ['Jordan', 78.35461813777415, -2.516590336161928, -30.237903530208975, 8.255964728505628, -11.945626383028152, -52.54961123531745, 92.39262344708006, 6.523893034147998], ['Chad', 39.79528145562019, 30.902742935368323, 3.3483635053675354, -5.364056680992324, 13.710746334714496, 40.53065836899212, 100.18711753216331, 41.46485332069594], ['Malta', -44.19743552016453, -36.69420412396413, 46.75257328483846, 58.722220946192614, -39.650737367154655, 87.31158723760504, 47.781432810250976, -11.24181350363842], ['Nigeria', -2.7975515027272135, 25.271994347447936, -27.175397081334797, -0.7126435714709278, -1.2139459333245672, 8.886996507690604, -17.332734404424667, -26.90962329553017], ['Sudan', -40.549772007148924, 51.32985153392418, 91.40833260239619, 62.84477760681475, -6.038605341156211, -5.385978077915931, 28.200362571062975, -11.936928798380542], ['Sri Lanka', 7.599049685140824, -11.960342149054847, 14.32373964506386, 6.720071612235201, -9.011230799915747, 3.6574386713610796, -11.40385860069303, 1.923525932226955], ['Kuwait', -27.828937385745345, -11.855961284498907, -25.65299205349928, 42.31867976378256, -8.628936398997578, -32.46796408939731, -63.635333576412776, 68.34606500711897], ['Kyrgyzstan', 12.352757443970974, -1.9133564118386626, 11.880028286631216, 17.799223687107713, -58.72290245858181, 20.635258394027424, 18.014347186693456, -19.410267587724483], ['Hong Kong', 1.1486622518492196, -16.687589488911748, 34.63278733827204, -17.81724614278336, 41.31612612910707, 73.99415920853514, -3.474546509065357, -74.96846233787473], ['Cambodia', 51.01368629100502, -14.359360732060388, -18.98859174340589, -4.285292786933548, 12.897863783267649, -9.1846499915483, -13.024729340564779, -6.916161286515388], ['Albania', 19.710755352514898, -46.296780647709404, -63.987670714303604, 30.20110630911985, -5.5216322601851715, -6.681062813678162, 50.78332843725939, 67.11528840149424], ['Cameroon', -10.080736498656485, -2.8198079122503827, 21.14686213123116, 15.084812950251592, -7.236616585237421, 7.047064608759035, -16.047507219391875, 23.720770048635465], ['Mali', 1990.063232970186, -76.18336322186174, 351.4184194621736, 193.66951489994105, -32.744100479517854, -56.96781853647016, -56.0717898604127, 1233.0059245154937], ['Lebanon', -27.41596096275486, -47.91077680813298, 15.714905734791662, 48.16469014922986, 31.068808427971284, -63.465584749736756, -19.754880567041976, -9.165144093632305], ['Costa Rica', -18.62225950768185, -57.52548271283293, 7.9521047283239055, -15.314116564727476, -29.329107308598434, 25.95960904058481, 16.79872574518504, -33.34367540731786], ['Myanmar', 26.74499152707788, -9.115801643196676, 7.688768177680294, 171.03576768745307, 51.674558873720635, 24.720320592528466, -7.283116786845767, -13.44317351271378], ['Mozambique', 9.654477902936808, 3.2682968948172686, 30.160059468472266, 45.599476210207925, -36.511690607971836, -22.028639626580638, -2.3297835685978874, -43.49939782821796], ['Tanzania', -21.13601661337664, 9.46693657451323, -38.70909386547696, 76.14599767455086, -15.20537744674062, -27.293833115726162, 66.98927251034392, -22.778840362637176], ['Marshall Islands', -67.75332133899371, 3803.6013751371365, -48.31778326972081, 202.92293136414133, -74.68362163007323, 155.0257655270423, 120.1121262075187, -13.759060402029688], ['Countries and territories not specified', -64.00176993141515, -44.268908715110946, 92.16352936920427, 365.486244744061, -43.900834441369696, -79.07644970539333, 1230.9526079196598, 33.357887796673324], ['Afghanistan', 70.73963247611093, -57.49737997561193, -1.920798612966923, 46.33953609615982, 12.748154794406164, -2.284346466540066, 13.492998386251331, 7.9477083720636665], ['New Zealand', 31.437805100136117, -37.47865432698876, -2.8966060077185274, -28.999278064709344, -17.45667780351482, 17.96778677091386, -28.144040739522502, -17.750302696349372], ['Togo', -1.5812338572709805, -81.44539660343023, -35.19843483157189, 122.06022291686706, 47.22979365147057, -41.120511370121314, 3.1422378398064055, 133.14540881830234], ['Iceland', 24.048658224639574, 22.11630734534049, -10.11823947479521, 16.668375817103964, -12.356905398809658, -6.223755631059813, -2.1587504482025066, -12.876417406966345], ['Dominican Rep.', -7.174956889438167, -0.33979793979614925, -21.599362879497853, 21.687584452504073, -3.110535610003007, -2.5659305924823683, 1.3959980638002856, 28.070856650669995], ['Seychelles', 424.48217327056807, 71.72039103028303, -44.720002970591565, 163.05317415452606, -32.92336224778576, -16.772197312294225, 16.222603993332683, 132.27681603673466], ['Gabon', -83.75753770292161, 6.815295578777891, -46.94429274557829, 102.70258195511887, 137.81518600128413, 1.511972418731511, 144.77205686700492, 0.714662003845179], ['Ethiopia', 8.9278548686212, -47.09759424561679, -7.8894389849768825, 0.6750253025001873, 1.6067776112149934, 30.424762419533913, -21.2812280822

In [25]:
countryImpchange

,Country,13/14,14/15,15/16,16/17,17/18,18/19,19/20,20/21
0,China,1.868962,-1.745358,-1.705683,-4.421413,-9.462306,-11.056641,20.457766,26.292681
1,Russia,-2.437331,-18.368116,-25.437719,29.932885,13.005527,1.781029,-22.867721,43.448226
2,Confidential Country,1.905181,-28.425215,-31.158825,21.935959,34.297497,37.938450,-9.799370,49.247949
3,Germany,-8.267307,-3.178055,-0.388468,-1.616881,-3.348742,-10.470402,12.719449,-9.160580
4,USA,0.857787,-13.827309,-2.820291,8.980541,5.755390,-8.836586,-2.721468,1.551381
...,...,...,...,...,...,...,...,...,...
233,Ceuta,-89.793693,-56.563454,879.618474,-100.000000,NaN,NaN,NaN,NaN
234,Melilla,-94.896900,-9.893666,-62.339661,-100.000000,NaN,NaN,NaN,NaN
235,Tonga,275.728155,-100.000000,NaN,NaN,NaN,NaN,NaN,NaN
236,Bouvet Islands,NaN,-100.000000,NaN,NaN,NaN,NaN,NaN,NaN
237,Stores and Provinces,-100.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
#check
len(data['Country'].unique()) == len(countryImpchange)

True

In [27]:
countryImpchange.to_excel(r'Imports_change.xls', index = False)